# Generated by Django 5.2 on 2025-04-11 19:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeputyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_endpoint", models.URLField(max_length=500)),
                ("api_key", models.CharField(help_text="encrypted", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "deputy_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeputyEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deputy_id", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "deputy_employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("required_security_role", models.CharField(max_length=20)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_location",
                    models.JSONField(
                        blank=True,
                        help_text="Latitude and longitude of check-in location",
                        null=True,
                    ),
                ),
                (
                    "check_out_location",
                    models.JSONField(
                        blank=True,
                        help_text="Latitude and longitude of check-out location",
                        null=True,
                    ),
                ),
                (
                    "start_signature",
                    models.TextField(blank=True, help_text="base64", null=True),
                ),
                (
                    "end_signature",
                    models.TextField(blank=True, help_text="base64", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("manager_approved", models.BooleanField(default=False)),
                (
                    "manager_signature",
                    models.TextField(blank=True, help_text="base64", null=True),
                ),
                ("manager_notes", models.TextField(blank=True, null=True)),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="whether venue terms were accepted for this shift",
                    ),
                ),
                (
                    "actual_hours_worked",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "break_duration",
                    models.IntegerField(
                        default=0, help_text="Break duration in minutes"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "shifts",
                "ordering": ["-start_time"],
                "permissions": [
                    ("can_approve_shifts", "Can approve shifts"),
                    ("can_view_all_shifts", "Can view all shifts"),
                    ("can_manage_shifts", "Can manage shifts"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Weekend Night Shift')",
                        max_length=255,
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(help_text="List of days this template applies to"),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("required_security_role", models.CharField(max_length=20)),
                ("min_staff_required", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="HEX color code for UI display",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "shift_templates",
                "ordering": ["venue", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                (
                    "national_insurance_number",
                    models.CharField(max_length=20, unique=True),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "profile_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "password_last_changed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("capacity", models.IntegerField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "check_radius",
                    models.IntegerField(
                        default=50,
                        help_text="Radius in meters for location verification",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                ("description", models.TextField(help_text="venue description")),
                (
                    "terms_and_conditions",
                    models.TextField(help_text="venue terms and conditions"),
                ),
                (
                    "terms_version",
                    models.CharField(
                        blank=True,
                        help_text="optional version identifier for terms",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "requires_fire_safety_checks",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this venue requires regular fire safety checks",
                    ),
                ),
                (
                    "requires_capacity_monitoring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this venue requires capacity monitoring",
                    ),
                ),
                (
                    "requires_toilet_checks",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this venue requires regular toilet checks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "venues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FireExitCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "photo_evidence",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text="Latitude and longitude of check location",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exit_name", models.CharField(max_length=255)),
                ("is_clear", models.BooleanField(default=True)),
                ("is_properly_marked", models.BooleanField(default=True)),
                ("is_accessible", models.BooleanField(default=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.shift"
                    ),
                ),
            ],
            options={
                "db_table": "fire_exit_checks",
            },
        ),
        migrations.CreateModel(
            name="DeputyTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deputy_id", models.CharField(max_length=100, unique=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "break_length",
                    models.IntegerField(help_text="Break length in minutes"),
                ),
                ("status", models.CharField(max_length=50)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="api.deputyemployee",
                    ),
                ),
                (
                    "mapped_to_shift",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deputy_timesheet",
                        to="api.shift",
                    ),
                ),
            ],
            options={
                "db_table": "deputy_timesheets",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="CapacityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "photo_evidence",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text="Latitude and longitude of check location",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("venue_capacity", models.IntegerField()),
                ("is_at_capacity", models.BooleanField(default=False)),
                ("action_taken", models.TextField(blank=True, null=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.shift"
                    ),
                ),
            ],
            options={
                "db_table": "capacity_checks",
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_shifts",
                to="api.shifttemplate",
            ),
        ),
        migrations.CreateModel(
            name="SIALicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("ds", "Door Supervisor"),
                            ("sg", "Security Guard"),
                            ("cctv", "CCTV Operator"),
                            ("cp", "Close Protection"),
                            ("k9", "Dog Handler"),
                            ("vs", "Vehicle Security"),
                            ("key", "Key Holding"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("trainee", "Trainee"),
                            ("qualified", "Qualified"),
                            ("advanced", "Advanced"),
                            ("instructor", "Instructor"),
                        ],
                        default="qualified",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="valid",
                        max_length=10,
                    ),
                ),
                ("document_url", models.URLField(max_length=500)),
                (
                    "additional_certifications",
                    models.JSONField(
                        default=list,
                        help_text="Additional certifications related to this license",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sia_licenses",
                        to="api.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sia_licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="api.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("sort_code", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="api.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "bank_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToiletCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "photo_evidence",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text="Latitude and longitude of check location",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("location_name", models.CharField(max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("needs_attention", models.BooleanField(default=False)),
                ("is_out_of_order", models.BooleanField(default=False)),
                ("supplies_needed", models.TextField(blank=True, null=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.shift"
                    ),
                ),
            ],
            options={
                "db_table": "toilet_checks",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=10,
                    ),
                ),
                (
                    "security_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of security roles for staff members",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="api_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="api_user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="ShiftStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="api.shift",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_status_changes",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "shift_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted_by_target", "Accepted by Target User"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_reason", models.TextField()),
                (
                    "target_response",
                    models.TextField(
                        blank=True, help_text="Response from target user", null=True
                    ),
                ),
                ("manager_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_requests",
                        to="api.shift",
                    ),
                ),
                (
                    "manager_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_exchanges",
                        to="api.user",
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_exchanges",
                        to="api.user",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_exchanges",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "shift_exchanges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="manager_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_shifts",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="staff_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="OpenShiftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("claimed", "Claimed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("request_reason", models.TextField()),
                ("claim_time", models.DateTimeField(blank=True, null=True)),
                ("manager_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_requests",
                        to="api.shift",
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_shifts",
                        to="api.user",
                    ),
                ),
                (
                    "manager_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_open_shifts",
                        to="api.user",
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_releases",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "open_shift_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_hours", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deputyemployee",
            name="mapped_to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deputy_employee",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_templates",
                to="api.venue",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="api.venue",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.invoice",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="api.shift",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_items",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="StaffAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="api.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "staff_availability",
                "ordering": ["day_of_week"],
                "unique_together": {("staff_profile", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="SecurityQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification_type",
                    models.CharField(
                        choices=[
                            ("first_aid", "First Aid"),
                            ("conflict_management", "Conflict Management"),
                            ("physical_intervention", "Physical Intervention"),
                            ("fire_safety", "Fire Safety"),
                            ("health_safety", "Health & Safety"),
                            ("customer_service", "Customer Service"),
                            ("radio_comms", "Radio Communications"),
                            ("emergency_response", "Emergency Response"),
                            ("crowd_management", "Crowd Management"),
                            ("risk_assessment", "Risk Assessment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("certificate_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("document_url", models.URLField(max_length=500)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="api.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "security_qualifications",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("staff_profile", "qualification_type", "certificate_number")
                },
            },
        ),
        migrations.AlterUniqueTogether(
            name="shifttemplate",
            unique_together={("venue", "name")},
        ),
        migrations.CreateModel(
            name="PreferredVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_venues",
                        to="api.staffprofile",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_by_staff",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "preferred_venues",
                "ordering": ["-created_at"],
                "unique_together": {("staff_profile", "venue")},
            },
        ),
        migrations.CreateModel(
            name="PayRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_rates",
                        to="api.user",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        help_text="null for default rate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_rates",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "pay_rates",
                "ordering": ["-created_at"],
                "unique_together": {("staff_user", "venue")},
            },
        ),
        migrations.CreateModel(
            name="VenueTermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms_version",
                    models.CharField(
                        help_text="version of terms accepted", max_length=50
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_terms_acceptances",
                        to="api.user",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptances",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "venue_terms_acceptance",
                "ordering": ["-accepted_at"],
                "unique_together": {("staff_user", "venue", "terms_version")},
            },
        ),
    ]
