# Generated by Django 5.2 on 2025-04-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("entry_count", models.IntegerField(default=0)),
                ("exit_count", models.IntegerField(default=0)),
                ("current_total", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_capacity_flows",
                        to="api.user",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_flows",
                        to="api.shift",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_flows",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "capacity_flows",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["venue", "timestamp"],
                        name="capacity_fl_venue_i_721f43_idx",
                    ),
                    models.Index(
                        fields=["shift", "timestamp"],
                        name="capacity_fl_shift_i_e394c4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_time", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actions_taken", models.TextField()),
                ("requires_followup", models.BooleanField(default=False)),
                ("followup_notes", models.TextField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_incidents",
                        to="api.user",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to="api.user",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="api.shift",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "incident_reports",
                "ordering": ["-incident_time"],
                "indexes": [
                    models.Index(
                        fields=["venue", "incident_time"],
                        name="incident_re_venue_i_64c574_idx",
                    ),
                    models.Index(
                        fields=["severity", "resolved"],
                        name="incident_re_severit_7a255c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LatenessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes_late", models.IntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledgement_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_lateness_records",
                        to="api.user",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lateness_records",
                        to="api.shift",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lateness_records",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "lateness_records",
                "indexes": [
                    models.Index(
                        fields=["staff_user", "created_at"],
                        name="lateness_re_staff_u_e1cd21_idx",
                    ),
                    models.Index(
                        fields=["shift", "created_at"],
                        name="lateness_re_shift_i_2e5678_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QualificationReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification_type",
                    models.CharField(
                        choices=[
                            ("sia", "SIA License"),
                            ("first_aid", "First Aid"),
                            ("security_qual", "Security Qualification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_date", models.DateField()),
                ("reminder_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_reminders",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "qualification_reminders",
                "ordering": ["expiry_date"],
                "indexes": [
                    models.Index(
                        fields=["staff_user", "expiry_date"],
                        name="qualificati_staff_u_e33d89_idx",
                    ),
                    models.Index(
                        fields=["reminder_date", "reminder_sent"],
                        name="qualificati_reminde_4976e8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VenueHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField()),
                ("issues_flagged", models.BooleanField(default=False)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_handovers",
                        to="api.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_handovers",
                        to="api.user",
                    ),
                ),
                (
                    "incoming_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_handovers",
                        to="api.shift",
                    ),
                ),
                (
                    "outgoing_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_handovers",
                        to="api.shift",
                    ),
                ),
            ],
            options={
                "db_table": "venue_handovers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["outgoing_shift", "created_at"],
                        name="venue_hando_outgoin_2d5f81_idx",
                    ),
                    models.Index(
                        fields=["incoming_shift", "acknowledged"],
                        name="venue_hando_incomin_b0d8a5_idx",
                    ),
                ],
            },
        ),
    ]
