# Generated by Django 5.2 on 2025-04-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_capacityflow_incidentreport_latenessrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Mead Security", max_length=255),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@meadsecurity.co.uk", max_length=255
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(default="+44 1234 567890", max_length=50),
                ),
                (
                    "default_hourly_rate",
                    models.DecimalField(decimal_places=2, default=15.5, max_digits=10),
                ),
                (
                    "default_payment_terms",
                    models.CharField(default="Net 30", max_length=100),
                ),
                ("invoice_prefix", models.CharField(default="MSD-", max_length=10)),
                ("automatic_invoicing", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=True)),
                ("shift_reminders", models.BooleanField(default=True)),
                ("invoice_reminders", models.BooleanField(default=True)),
                ("report_generation", models.BooleanField(default=False)),
                ("require_signatures", models.BooleanField(default=True)),
                ("require_manager_approval", models.BooleanField(default=True)),
                ("require_shift_photos", models.BooleanField(default=False)),
                ("session_timeout", models.IntegerField(default=30)),
                ("allow_shift_exchange", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
