# Generated by Django 5.2 on 2025-04-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="special_event_pay_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="Default rate for special event shifts",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="default_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=15.5,
                help_text="Default rate for regular shifts",
                max_digits=10,
            ),
        ),
    ]
