# Generated by Django 5.2 on 2025-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_systemsettings_special_event_pay_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin approval required before staff can take shifts",
            ),
        ),
    ]
