# Generated by Django 5.2 on 2025-07-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_staffprofile_is_approved"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("venue", "staff_user", "start_time", "end_time")},
        ),
    ]
