# Generated by Django 5.2 on 2025-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_unique_constraint_to_shifts"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_group",
            field=models.CharField(
                blank=True,
                help_text="Groups multiple staff shifts for the same venue/time",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("shift_group", "staff_user")},
        ),
    ]
