# Generated by Django 5.2 on 2025-07-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_shift_group_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
    ]
