# Generated by Django 5.2 on 2025-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_shift_group_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
