# Generated by Django 5.2 on 2025-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_update_venue_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=14, max_digits=17, null=True
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=14, max_digits=17, null=True
            ),
        ),
    ]
