# Generated by Django 5.2 on 2025-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_venue_latitude_alter_venue_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=18, null=True
            ),
        ),
    ]
