# Generated by Django 5.2 on 2025-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_venue_latitude_alter_venue_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="check_in_photo",
            field=models.TextField(blank=True, help_text="base64", null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="check_out_photo",
            field=models.TextField(blank=True, help_text="base64", null=True),
        ),
    ]
