# Generated by Django 5.2 on 2025-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_shift_check_in_photo_shift_check_out_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly pay rate for this shift",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="is_special_event",
            field=models.BooleanField(
                default=False, help_text="Whether this shift is for a special event"
            ),
        ),
    ]
