# Generated by Django 5.2 on 2025-07-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_shift_hourly_rate_shift_is_special_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="auto_checkout",
            field=models.BooleanField(
                default=False,
                help_text="Whether this shift was automatically checked out",
            ),
        ),
    ]
