# Generated by Django 5.2 on 2025-07-11 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_add_auto_checkout_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Employment type name (e.g., 'Contract Workers', 'Temporary Staff')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of this employment type"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this employment type is currently available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employment_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("home_address", models.TextField()),
                ("postcode", models.CharField(max_length=20)),
                ("has_sia_licence", models.BooleanField(default=False)),
                (
                    "sia_licence_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "licence_types",
                    models.JSONField(
                        default=list, help_text="List of licence types held"
                    ),
                ),
                ("licence_expiry_date", models.DateField(blank=True, null=True)),
                ("licence_suspended_revoked", models.BooleanField(default=False)),
                ("licence_suspension_details", models.TextField(blank=True, null=True)),
                (
                    "hours_per_week",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("availability_days", models.BooleanField(default=False)),
                ("availability_nights", models.BooleanField(default=False)),
                ("availability_weekends", models.BooleanField(default=False)),
                ("availability_holidays", models.BooleanField(default=False)),
                ("willing_to_travel", models.BooleanField(default=False)),
                ("has_transport", models.BooleanField(default=False)),
                ("has_commitments", models.BooleanField(default=False)),
                ("commitments_details", models.TextField(blank=True, null=True)),
                ("has_security_experience", models.BooleanField(default=False)),
                (
                    "security_experience_details",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=list, help_text="List of certifications held"
                    ),
                ),
                (
                    "other_certification_details",
                    models.TextField(blank=True, null=True),
                ),
                ("eligible_to_work_uk", models.BooleanField(default=False)),
                ("has_criminal_convictions", models.BooleanField(default=False)),
                (
                    "criminal_convictions_details",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "digital_signature",
                    models.TextField(help_text="base64 encoded signature"),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="api.employmenttype",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
