# Generated by Django 5.2 on 2025-07-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_employmenttype_recruitmentapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="employment_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Employment type for this staff member",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="api.employmenttype",
            ),
        ),
    ]
