# Generated by Django 5.2 on 2025-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_staffprofile_employment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="national_insurance_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
