# Generated by Django 5.2 on 2025-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_make_ni_number_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="auto_checkout_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable automatic checkout system"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="auto_checkout_force_timeout",
            field=models.IntegerField(
                default=720,
                help_text="Minutes after scheduled end time for force timeout (bypassing venue checks)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="auto_checkout_grace_period",
            field=models.IntegerField(
                default=30,
                help_text="Minutes after scheduled end time before auto-checkout is allowed",
            ),
        ),
    ]
