# Generated by Django 5.2 on 2025-07-13 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_add_auto_checkout_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftexchange",
            name="target_shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift offered by target user in exchange",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_exchange_requests",
                to="api.shift",
            ),
        ),
    ]
