# Generated by Django 5.2 on 2025-07-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_shiftexchange_target_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnforcementVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "officer_name",
                    models.CharField(
                        help_text="Name of the visiting officer", max_length=100
                    ),
                ),
                (
                    "officer_badge",
                    models.CharField(
                        help_text="Badge/ID number of the officer", max_length=50
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(help_text="Reason for the enforcement visit"),
                ),
                (
                    "action_taken",
                    models.TextField(help_text="Actions taken during the visit"),
                ),
                ("outcome", models.TextField(help_text="Outcome of the visit")),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enforcement_visits",
                        to="api.shift",
                    ),
                ),
            ],
            options={
                "db_table": "enforcement_visits",
                "ordering": ["-timestamp"],
            },
        ),
    ]
