# Generated by Django 5.2 on 2025-09-16 13:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_add_enforcement_visit_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingHoursRegulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g., 'GB', 'US', 'FR')",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        help_text="Full country name for display purposes",
                        max_length=100,
                    ),
                ),
                (
                    "standard_weekly_hours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Standard weekly working hours (e.g., 40.0 for UK/US, 35.0 for France)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "standard_daily_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=8.0,
                        help_text="Standard daily working hours",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "overtime_threshold_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weekly hours threshold before overtime applies",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overtime_multiplier_1",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="First overtime rate multiplier (e.g., 1.5 for time-and-a-half)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "overtime_threshold_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Second overtime threshold for higher rates (optional)",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overtime_multiplier_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Second overtime rate multiplier (e.g., 2.0 for double time)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "max_daily_hours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Maximum allowed daily working hours",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "max_weekly_hours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Maximum allowed weekly working hours",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Maximum consecutive working days allowed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "min_rest_between_shifts_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=11.0,
                        help_text="Minimum rest hours required between shifts",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "min_weekly_rest_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=24.0,
                        help_text="Minimum weekly continuous rest period",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "break_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Required break duration in minutes for standard shifts",
                        validators=[django.core.validators.MaxValueValidator(480)],
                    ),
                ),
                (
                    "break_trigger_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=6.0,
                        help_text="Shift length that triggers break requirement",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "special_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional country-specific rules as JSON (e.g., night shift premiums, holiday rules)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this regulation is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Working Hours Regulation",
                "verbose_name_plural": "Working Hours Regulations",
                "db_table": "working_hours_regulations",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Profile name for identification (e.g., 'UK Security Operations')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this compliance profile and its intended use",
                    ),
                ),
                (
                    "override_max_daily_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Override max daily hours (must be <= regulation max)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "override_max_weekly_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Override max weekly hours (must be <= regulation max)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "override_max_consecutive_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override max consecutive days (must be <= regulation max)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "daily_hours_warning_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Percentage of daily limit that triggers warning (e.g., 80.00 for 80%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(99.99),
                        ],
                    ),
                ),
                (
                    "weekly_hours_warning_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=85.0,
                        help_text="Percentage of weekly limit that triggers warning",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(99.99),
                        ],
                    ),
                ),
                (
                    "consecutive_days_warning_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of consecutive days that triggers warning",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ],
                    ),
                ),
                (
                    "auto_approve_overtime",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically approve overtime shifts within compliance limits",
                    ),
                ),
                (
                    "auto_approve_extended_hours",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically approve extended daily hours within limits",
                    ),
                ),
                (
                    "require_manager_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Require manager approval for shifts that may cause violations",
                    ),
                ),
                (
                    "notify_on_warnings",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications when warning thresholds are reached",
                    ),
                ),
                (
                    "notify_on_violations",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications when violations occur",
                    ),
                ),
                (
                    "notification_recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of email addresses to receive compliance notifications",
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Grace period in minutes for minor timing violations",
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "allow_break_flexibility",
                    models.BooleanField(
                        default=True,
                        help_text="Allow flexible break scheduling within shifts",
                    ),
                ),
                (
                    "custom_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom compliance rules specific to this organization",
                    ),
                ),
                (
                    "exception_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User roles exempt from certain compliance checks",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "working_hours_regulation",
                    models.ForeignKey(
                        help_text="Base working hours regulation for this profile",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_profiles",
                        to="api.workinghoursregulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Profile",
                "verbose_name_plural": "Compliance Profiles",
                "db_table": "compliance_profiles",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("daily_overtime", "Daily Hours Exceeded"),
                            ("weekly_overtime", "Weekly Hours Exceeded"),
                            ("consecutive_days", "Too Many Consecutive Days"),
                            ("insufficient_rest", "Insufficient Rest Between Shifts"),
                            ("missing_break", "Required Break Not Taken"),
                            ("late_checkin", "Late Check-in"),
                            ("early_checkout", "Early Check-out"),
                            ("location_violation", "Location Compliance Violation"),
                            ("unauthorized_overtime", "Unauthorized Overtime"),
                            ("shift_abandonment", "Shift Abandonment"),
                            ("documentation_missing", "Missing Required Documentation"),
                            ("custom", "Custom Violation Type"),
                        ],
                        help_text="Type of compliance violation",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("minor", "Minor Violation"),
                            ("major", "Major Violation"),
                            ("critical", "Critical Violation"),
                        ],
                        default="warning",
                        help_text="Severity level of the violation",
                        max_length=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        help_text="Start of the time period when violation occurred"
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        help_text="End of the time period when violation occurred"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the violation"),
                ),
                (
                    "calculated_values",
                    models.JSONField(
                        default=dict,
                        help_text="Calculated values that triggered the violation (hours, limits, etc.)",
                    ),
                ),
                (
                    "threshold_exceeded",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount by which threshold was exceeded",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "evidence_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Supporting evidence and data for the violation",
                    ),
                ),
                (
                    "system_generated",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this violation was automatically detected by the system",
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Under Investigation"),
                            ("pending_approval", "Pending Manager Approval"),
                            ("approved_exception", "Approved as Exception"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        help_text="Current status of violation resolution",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the resolution or investigation",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the violation was resolved",
                        null=True,
                    ),
                ),
                (
                    "exception_granted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an exception was granted for this violation",
                    ),
                ),
                (
                    "exception_reason",
                    models.TextField(
                        blank=True, help_text="Reason for granting exception"
                    ),
                ),
                (
                    "financial_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Financial impact of the violation (overtime costs, penalties, etc.)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "compliance_score_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Impact on overall compliance score",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved the exception",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_shifts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other shifts that contributed to this violation",
                        related_name="contributing_violations",
                        to="api.shift",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who resolved the violation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific shift related to violation (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_violations",
                        to="api.shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Staff member involved in the violation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Violation",
                "verbose_name_plural": "Compliance Violations",
                "db_table": "compliance_violations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="compliance__user_id_d18fd9_idx",
                    ),
                    models.Index(
                        fields=["violation_type", "-created_at"],
                        name="compliance__violati_65f253_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="compliance__severit_e29bc9_idx",
                    ),
                    models.Index(
                        fields=["resolution_status"],
                        name="compliance__resolut_241699_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="compliance__period__c906e5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHoursMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="Type of time period for aggregation",
                        max_length=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start date of the period"),
                ),
                ("period_end", models.DateField(help_text="End date of the period")),
                (
                    "total_hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours worked in the period",
                        max_digits=6,
                    ),
                ),
                (
                    "regular_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Regular hours worked (within standard limits)",
                        max_digits=6,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overtime hours worked",
                        max_digits=6,
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total break time taken",
                        max_digits=5,
                    ),
                ),
                (
                    "total_shifts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of shifts worked"
                    ),
                ),
                (
                    "completed_shifts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed shifts"
                    ),
                ),
                (
                    "cancelled_shifts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of cancelled shifts"
                    ),
                ),
                (
                    "average_shift_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average duration of shifts in hours",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "violation_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of compliance violations in this period",
                    ),
                ),
                (
                    "warning_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of compliance warnings in this period",
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Overall compliance score for the period (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "adequate_rest_periods",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of shifts with adequate rest before",
                    ),
                ),
                (
                    "insufficient_rest_periods",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of shifts with insufficient rest before",
                    ),
                ),
                (
                    "consecutive_working_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum consecutive working days in period",
                    ),
                ),
                (
                    "estimated_regular_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated regular pay for the period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "estimated_overtime_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated overtime pay for the period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_estimated_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total estimated pay for the period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "punctuality_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Punctuality score based on on-time arrivals (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Attendance rate for scheduled shifts (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "venues_worked",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of different venues worked at"
                    ),
                ),
                (
                    "shift_types_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Breakdown of hours by shift type",
                    ),
                ),
                (
                    "detailed_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional detailed metrics and breakdowns",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "calculation_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of calculation algorithm used",
                        max_length=20,
                    ),
                ),
                (
                    "needs_recalculation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether metrics need to be recalculated due to data changes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Staff member for these metrics",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Working Hours Metrics",
                "verbose_name_plural": "Working Hours Metrics",
                "db_table": "working_hours_metrics",
                "ordering": ["-period_start", "user"],
                "indexes": [
                    models.Index(
                        fields=["user", "-period_start"],
                        name="working_hou_user_id_2a4645_idx",
                    ),
                    models.Index(
                        fields=["period_type", "-period_start"],
                        name="working_hou_period__99377f_idx",
                    ),
                    models.Index(
                        fields=["compliance_score"],
                        name="working_hou_complia_9b596d_idx",
                    ),
                    models.Index(
                        fields=["violation_count"],
                        name="working_hou_violati_ea51b4_idx",
                    ),
                    models.Index(
                        fields=["needs_recalculation"],
                        name="working_hou_needs_r_89d5d5_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "period_type", "period_start", "period_end")
                },
            },
        ),
    ]
