# Generated by Django ORM Expert - Compliance System Performance Optimizations

from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension
from django.contrib.postgres.indexes import GinIndex, BrinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_workinghoursregulation_complianceprofile_and_more'),
    ]

    operations = [
        # Enable PostgreSQL extensions for advanced indexing
        BtreeGinExtension(),

        # Advanced indexes for high-performance compliance queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compliance_violations_reporting_idx ON compliance_violations (user_id, period_start DESC, resolution_status, severity) WHERE resolution_status IN ('open', 'investigating', 'pending_approval');",
            reverse_sql="DROP INDEX IF EXISTS compliance_violations_reporting_idx;"
        ),

        # Composite index for real-time compliance checking
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compliance_violations_realtime_check_idx ON compliance_violations (user_id, violation_type, period_end DESC) WHERE resolution_status IN ('open', 'investigating');",
            reverse_sql="DROP INDEX IF EXISTS compliance_violations_realtime_check_idx;"
        ),

        # Manager dashboard optimization - violations by status and severity
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compliance_violations_dashboard_idx ON compliance_violations (resolution_status, severity, created_at DESC) WHERE resolution_status != 'resolved';",
            reverse_sql="DROP INDEX IF EXISTS compliance_violations_dashboard_idx;"
        ),

        # Time-based reporting optimization with BRIN index for large datasets
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compliance_violations_time_brin_idx ON compliance_violations USING BRIN (period_start, period_end);",
            reverse_sql="DROP INDEX IF EXISTS compliance_violations_time_brin_idx;"
        ),

        # Working hours metrics bulk calculation optimization
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS working_hours_metrics_bulk_calc_idx ON working_hours_metrics (user_id, period_type, needs_recalculation) WHERE needs_recalculation = true;",
            reverse_sql="DROP INDEX IF EXISTS working_hours_metrics_bulk_calc_idx;"
        ),

        # Performance reporting - metrics by period range
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS working_hours_metrics_period_range_idx ON working_hours_metrics (period_start, period_end, period_type) INCLUDE (compliance_score, violation_count, total_hours_worked);",
            reverse_sql="DROP INDEX IF EXISTS working_hours_metrics_period_range_idx;"
        ),

        # Shifts compliance correlation index
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS shifts_compliance_check_idx ON shifts (staff_user_id, start_time DESC, status) WHERE status IN ('completed', 'approved');",
            reverse_sql="DROP INDEX IF EXISTS shifts_compliance_check_idx;"
        ),

        # JSON field optimization for special rules and calculated values
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compliance_violations_calculated_values_gin ON compliance_violations USING GIN (calculated_values);",
            reverse_sql="DROP INDEX IF EXISTS compliance_violations_calculated_values_gin;"
        ),

        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compliance_profile_custom_rules_gin ON compliance_profiles USING GIN (custom_rules);",
            reverse_sql="DROP INDEX IF EXISTS compliance_profile_custom_rules_gin;"
        ),

        # Database constraints for business rules
        migrations.RunSQL(
            "ALTER TABLE compliance_violations ADD CONSTRAINT check_period_order CHECK (period_start <= period_end);",
            reverse_sql="ALTER TABLE compliance_violations DROP CONSTRAINT IF EXISTS check_period_order;"
        ),

        migrations.RunSQL(
            "ALTER TABLE compliance_violations ADD CONSTRAINT check_threshold_positive CHECK (threshold_exceeded IS NULL OR threshold_exceeded >= 0);",
            reverse_sql="ALTER TABLE compliance_violations DROP CONSTRAINT IF EXISTS check_threshold_positive;"
        ),

        migrations.RunSQL(
            "ALTER TABLE working_hours_metrics ADD CONSTRAINT check_metrics_period_order CHECK (period_start <= period_end);",
            reverse_sql="ALTER TABLE working_hours_metrics DROP CONSTRAINT IF EXISTS check_metrics_period_order;"
        ),

        migrations.RunSQL(
            "ALTER TABLE working_hours_metrics ADD CONSTRAINT check_hours_non_negative CHECK (total_hours_worked >= 0 AND regular_hours >= 0 AND overtime_hours >= 0);",
            reverse_sql="ALTER TABLE working_hours_metrics DROP CONSTRAINT IF EXISTS check_hours_non_negative;"
        ),

        # Database functions for complex calculations
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION calculate_overtime_hours(
                regular_hours DECIMAL(6,2),
                total_hours DECIMAL(6,2),
                threshold_hours DECIMAL(4,1),
                multiplier_1 DECIMAL(3,2),
                threshold_2 DECIMAL(4,1) DEFAULT NULL,
                multiplier_2 DECIMAL(3,2) DEFAULT NULL
            ) RETURNS DECIMAL(8,2) AS $$
            DECLARE
                overtime_hours DECIMAL(6,2);
                overtime_1 DECIMAL(6,2) := 0;
                overtime_2 DECIMAL(6,2) := 0;
            BEGIN
                overtime_hours := GREATEST(0, total_hours - threshold_hours);

                IF overtime_hours > 0 THEN
                    -- First tier overtime
                    IF threshold_2 IS NULL OR total_hours <= threshold_2 THEN
                        overtime_1 := overtime_hours * multiplier_1;
                    ELSE
                        -- Split between first and second tier
                        overtime_1 := (threshold_2 - threshold_hours) * multiplier_1;
                        overtime_2 := (total_hours - threshold_2) * COALESCE(multiplier_2, multiplier_1);
                    END IF;
                END IF;

                RETURN overtime_1 + overtime_2;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS calculate_overtime_hours;"
        ),

        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION calculate_compliance_score(
                violation_count INTEGER,
                warning_count INTEGER,
                total_shifts INTEGER
            ) RETURNS DECIMAL(5,2) AS $$
            DECLARE
                base_score DECIMAL(5,2) := 100.0;
                violation_penalty DECIMAL(5,2);
                warning_penalty DECIMAL(5,2);
            BEGIN
                -- Avoid division by zero
                IF total_shifts = 0 THEN
                    RETURN base_score;
                END IF;

                -- Calculate penalties
                violation_penalty := (violation_count::DECIMAL / total_shifts) * 20.0;
                warning_penalty := (warning_count::DECIMAL / total_shifts) * 5.0;

                -- Apply penalties with floor at 0
                RETURN GREATEST(0, base_score - violation_penalty - warning_penalty);
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS calculate_compliance_score;"
        ),

        # Trigger for automatic violation detection on shift completion
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION check_shift_compliance() RETURNS TRIGGER AS $$
            DECLARE
                daily_hours DECIMAL(5,2);
                weekly_hours DECIMAL(5,2);
                consecutive_days INTEGER;
                rest_hours DECIMAL(5,2);
                profile_id INTEGER;
                regulation_id INTEGER;
            BEGIN
                -- Only check compliance for completed/approved shifts
                IF NEW.status NOT IN ('completed', 'approved') THEN
                    RETURN NEW;
                END IF;

                -- Get active compliance profile
                SELECT id INTO profile_id FROM compliance_profiles WHERE is_active = true LIMIT 1;

                IF profile_id IS NULL THEN
                    RETURN NEW;
                END IF;

                -- Calculate daily hours for shift date
                SELECT COALESCE(SUM(actual_hours_worked), 0) INTO daily_hours
                FROM shifts
                WHERE staff_user_id = NEW.staff_user_id
                    AND DATE(start_time) = DATE(NEW.start_time)
                    AND status IN ('completed', 'approved');

                -- Calculate weekly hours
                SELECT COALESCE(SUM(actual_hours_worked), 0) INTO weekly_hours
                FROM shifts
                WHERE staff_user_id = NEW.staff_user_id
                    AND start_time >= DATE_TRUNC('week', NEW.start_time)
                    AND start_time < DATE_TRUNC('week', NEW.start_time) + INTERVAL '7 days'
                    AND status IN ('completed', 'approved');

                -- Check for violations and create records as needed
                -- This is a simplified version - full implementation would include
                -- detailed violation detection logic

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS check_shift_compliance;"
        ),

        migrations.RunSQL(
            "CREATE TRIGGER shift_compliance_check AFTER UPDATE ON shifts FOR EACH ROW WHEN (OLD.status != NEW.status) EXECUTE FUNCTION check_shift_compliance();",
            reverse_sql="DROP TRIGGER IF EXISTS shift_compliance_check ON shifts;"
        ),
    ]