# Generated by Django 5.2 on 2025-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_compliance_performance_optimizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinghoursregulation",
            name="break_requirements",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Break requirements mapped by shift duration (e.g., {'6_hours': {'duration_minutes': 20, 'paid': True}})",
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="industry_specific_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional industry-specific compliance rules beyond general labor law",
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="last_regulatory_update",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of last update to regulatory data"
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="night_shift_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Night work specific limitations and requirements (max hours, health assessments, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="opt_out_provisions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Working time directive opt-out rules and requirements (written agreements, notice periods, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="regulatory_source",
            field=models.CharField(
                blank=True,
                help_text="Source of regulatory information (e.g., 'UK Health and Safety Executive', 'FLSA')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="security_sector_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Security industry specific rules and requirements (SIA licensing, specialized training, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="workinghoursregulation",
            name="state_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="US state-specific labor law overrides and additional requirements",
            ),
        ),
    ]
