# Generated by Django 5.2 on 2025-09-23 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_enhance_working_hours_regulation_for_regional_compliance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the report template", max_length=200
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("compliance_summary", "Compliance Summary"),
                            ("violation_detail", "Violation Detail Report"),
                            ("working_hours", "Working Hours Report"),
                            ("venue_performance", "Venue Performance"),
                            ("staff_compliance", "Staff Compliance"),
                            ("trends_analysis", "Trends Analysis"),
                        ],
                        help_text="Type of report this template generates",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this report shows"
                    ),
                ),
                (
                    "sql_query",
                    models.TextField(
                        help_text="SQL query for generating report data (use parameterized queries)"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parameter definitions for the report (e.g., date ranges, filters)",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles that can use this template (e.g., ['admin', 'manager'])",
                    ),
                ),
                (
                    "template_config",
                    models.JSONField(
                        default=dict,
                        help_text="Additional configuration for report formatting and behavior",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_venues",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific venues this template applies to (empty = all venues)",
                        to="api.venue",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this report job",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the report generation",
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        help_text="Format for the exported report",
                        max_length=10,
                    ),
                ),
                (
                    "date_range_start",
                    models.DateTimeField(help_text="Start date for report data"),
                ),
                (
                    "date_range_end",
                    models.DateTimeField(help_text="End date for report data"),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Additional filters applied to the report",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When report generation started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When report generation completed",
                        null=True,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the generated report file",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of the generated file in bytes",
                        null=True,
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this report has been downloaded",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this report file expires and should be deleted"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who requested this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template used for this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "report_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["template_type", "is_active"],
                name="report_temp_templat_88b28a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["created_by"], name="report_temp_created_5c0da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["-created_at"], name="report_temp_created_c35fb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportjob",
            index=models.Index(
                fields=["requested_by", "-created_at"],
                name="report_jobs_request_08f3e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportjob",
            index=models.Index(
                fields=["status", "created_at"], name="report_jobs_status_a52eae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportjob",
            index=models.Index(
                fields=["expires_at"], name="report_jobs_expires_84d61b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportjob",
            index=models.Index(fields=["job_id"], name="report_jobs_job_id_fd051a_idx"),
        ),
    ]
