# Generated by Django 5.2 on 2025-09-24 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_reporting_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this export configuration", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this export configuration"
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        help_text="Export format this configuration applies to",
                        max_length=10,
                    ),
                ),
                (
                    "filename_pattern",
                    models.CharField(
                        default="{report_type}_{date_range}_{timestamp}",
                        help_text="Pattern for naming exported files (supports variables)",
                        max_length=200,
                    ),
                ),
                (
                    "compression",
                    models.CharField(
                        choices=[
                            ("none", "No Compression"),
                            ("zip", "ZIP"),
                            ("gzip", "GZIP"),
                        ],
                        default="none",
                        help_text="Compression method for exported files",
                        max_length=10,
                    ),
                ),
                (
                    "template_settings",
                    models.JSONField(
                        default=dict,
                        help_text="General template settings for this export format",
                    ),
                ),
                (
                    "pdf_settings",
                    models.JSONField(
                        default=dict,
                        help_text="PDF-specific settings (DPI, page size, margins, etc.)",
                    ),
                ),
                (
                    "excel_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Excel-specific settings (sheet names, formatting, charts, etc.)",
                    ),
                ),
                (
                    "csv_settings",
                    models.JSONField(
                        default=dict,
                        help_text="CSV-specific settings (delimiter, encoding, headers, etc.)",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum file size in MB before compression/splitting",
                    ),
                ),
                (
                    "enable_charts",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include charts in exports (where supported)",
                    ),
                ),
                (
                    "enable_formatting",
                    models.BooleanField(
                        default=True, help_text="Whether to apply advanced formatting"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default configuration for this format",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        default=list, help_text="Roles that can use this configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "export_configurations",
                "ordering": ["export_format", "name"],
                "indexes": [
                    models.Index(
                        fields=["export_format", "is_default"],
                        name="export_conf_export__d784e8_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="export_conf_is_defa_fb596d_idx"
                    ),
                ],
                "unique_together": {("export_format", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this scheduled report", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this scheduled report does",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        help_text="How often this report should be generated",
                        max_length=20,
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        help_text="When this report should next be generated"
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this report was last generated",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this scheduled report is active",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to send reports to",
                    ),
                ),
                (
                    "delivery_methods",
                    models.JSONField(
                        default=list,
                        help_text="List of delivery methods (email, webhook, storage)",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL for report delivery notifications",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parameters to use when generating the report",
                    ),
                ),
                (
                    "export_formats",
                    models.JSONField(
                        default=list,
                        help_text="List of formats to generate (pdf, excel, csv, json)",
                    ),
                ),
                (
                    "include_empty_reports",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send reports even when no data is found",
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=30,
                        help_text="How long to keep generated report files (days)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this scheduled report",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template to use for generating reports",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_reports",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["next_run", "is_active"],
                        name="scheduled_r_next_ru_e3af0b_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="scheduled_r_created_481947_idx"
                    ),
                    models.Index(
                        fields=["frequency", "is_active"],
                        name="scheduled_r_frequen_d6d8fa_idx",
                    ),
                ],
            },
        ),
    ]
