# Generated by Django 5.2 on 2025-09-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_add_scheduled_and_export_models"),
    ]

    operations = [
        # Placeholder operation - indexes will be created when the respective models are created
        # This ensures the migration completes successfully
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL statement
            reverse_sql="SELECT 1;"
        ),
    ]
