# Generated by Django 5.2 on 2025-09-25 00:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_add_websocket_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Official company name", max_length=255),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="Trading name if different from official name",
                        max_length=255,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Company registration number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, help_text="Tax ID or VAT number", max_length=50
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 country code", max_length=3
                    ),
                ),
                (
                    "state_province",
                    models.CharField(
                        blank=True, help_text="State or province", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Primary city of operations", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(help_text="Postal or ZIP code", max_length=20),
                ),
                (
                    "address_line_1",
                    models.CharField(help_text="Primary address", max_length=255),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Secondary address (suite, floor, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "industry_type",
                    models.CharField(
                        choices=[
                            ("events", "Event Security"),
                            ("retail", "Retail Security"),
                            ("corporate", "Corporate Security"),
                            ("construction", "Construction Security"),
                            ("healthcare", "Healthcare Security"),
                            ("education", "Education Security"),
                            ("hospitality", "Hospitality Security"),
                            ("transport", "Transport Security"),
                            ("mixed", "Mixed Services"),
                        ],
                        default="mixed",
                        help_text="Primary industry focus",
                        max_length=20,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("small", "1-10 employees"),
                            ("medium", "11-50 employees"),
                            ("large", "51-200 employees"),
                            ("enterprise", "200+ employees"),
                        ],
                        default="small",
                        help_text="Current company size",
                        max_length=20,
                    ),
                ),
                (
                    "staff_capacity",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum number of staff members allowed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "venue_capacity",
                    models.IntegerField(
                        default=20,
                        help_text="Maximum number of venues allowed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                            ("custom", "Custom"),
                        ],
                        default="starter",
                        help_text="Current subscription tier",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When subscription started",
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription ends (null for active subscriptions)",
                        null=True,
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        help_text="Email for billing and invoices", max_length=254
                    ),
                ),
                (
                    "primary_contact_name",
                    models.CharField(
                        help_text="Name of primary contact person", max_length=255
                    ),
                ),
                (
                    "primary_contact_email",
                    models.EmailField(
                        help_text="Email of primary contact person", max_length=254
                    ),
                ),
                (
                    "primary_contact_phone",
                    models.CharField(
                        help_text="Phone number of primary contact", max_length=20
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Company timezone for shift scheduling",
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency for billing and payments",
                        max_length=3,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "features_enabled",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary of enabled features for this company",
                    ),
                ),
                (
                    "custom_settings",
                    models.JSONField(
                        default=dict, help_text="Company-specific custom settings"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the company account is active"
                    ),
                ),
                (
                    "is_trial",
                    models.BooleanField(
                        default=False, help_text="Whether this is a trial account"
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True, help_text="When trial period ends", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated compliance profile for regulatory requirements",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.complianceprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this company",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Company",
                "verbose_name_plural": "Security Companies",
                "db_table": "security_companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_steps", models.IntegerField(default=5)),
                ("company_info_completed", models.BooleanField(default=False)),
                ("regional_setup_completed", models.BooleanField(default=False)),
                ("staff_setup_completed", models.BooleanField(default=False)),
                ("integrations_completed", models.BooleanField(default=False)),
                ("finalization_completed", models.BooleanField(default=False)),
                (
                    "step_data",
                    models.JSONField(
                        default=dict,
                        help_text="Temporary storage for step data during onboarding",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        default=dict, help_text="Validation errors for each step"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Browser session ID for onboarding continuity",
                        max_length=100,
                    ),
                ),
                (
                    "last_step_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user last accessed any step",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When onboarding was fully completed",
                        null=True,
                    ),
                ),
                (
                    "time_spent_minutes",
                    models.IntegerField(
                        default=0, help_text="Total time spent in onboarding (minutes)"
                    ),
                ),
                (
                    "estimated_time_remaining",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated remaining time in minutes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed the onboarding",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboardings_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="api.securitycompany",
                    ),
                ),
            ],
            options={
                "db_table": "company_onboarding",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("deputy", "Deputy Workforce Management"),
                            ("payroll", "Payroll System"),
                            ("accounting", "Accounting Software"),
                            ("crm", "Customer Relationship Management"),
                            ("security", "Security Monitoring"),
                            ("communication", "Communication Platform"),
                            ("analytics", "Analytics Platform"),
                            ("custom", "Custom Integration"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this integration", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this integration does",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Integration-specific configuration settings",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text="Encrypted credentials for the integration",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Not Configured"),
                            ("configuring", "Being Configured"),
                            ("testing", "Testing Connection"),
                            ("active", "Active"),
                            ("error", "Configuration Error"),
                            ("suspended", "Temporarily Suspended"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this integration is enabled"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When data was last synchronized",
                        null=True,
                    ),
                ),
                (
                    "last_health_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="When connection was last tested",
                        null=True,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message if any"),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive errors"
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("manual", "Manual only"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether automatic syncing is enabled"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        help_text="User who configured this integration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrations_configured",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="api.securitycompany",
                    ),
                ),
            ],
            options={
                "db_table": "company_integrations",
                "ordering": ["integration_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="venue",
            name="company",
            field=models.ForeignKey(
                help_text="Company that owns this venue",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="api.securitycompany",
            ),
        ),
        migrations.CreateModel(
            name="UserCompanyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Company Owner"),
                            ("admin", "Company Administrator"),
                            ("manager", "Manager"),
                            ("staff", "Staff Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user is the company owner",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this membership is currently active",
                    ),
                ),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Invitation Pending"),
                            ("accepted", "Invitation Accepted"),
                            ("declined", "Invitation Declined"),
                            ("expired", "Invitation Expired"),
                        ],
                        default="accepted",
                        help_text="Status of the membership invitation",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation was sent", null=True
                    ),
                ),
                (
                    "invitation_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation expires", null=True
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict, help_text="Custom permissions for this membership"
                    ),
                ),
                (
                    "access_restrictions",
                    models.JSONField(
                        default=dict, help_text="Any access restrictions for this user"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user last accessed this company's data",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.securitycompany",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_company_memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="securitycompany",
            index=models.Index(
                fields=["country_code"], name="security_co_country_688fda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitycompany",
            index=models.Index(
                fields=["subscription_tier"], name="security_co_subscri_8e4b43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitycompany",
            index=models.Index(
                fields=["is_active"], name="security_co_is_acti_671c8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitycompany",
            index=models.Index(
                fields=["registration_number"], name="security_co_registr_6679eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyonboarding",
            index=models.Index(
                fields=["company", "current_step"],
                name="company_onb_company_196822_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyonboarding",
            index=models.Index(
                fields=["completed_at"], name="company_onb_complet_fa0dc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyonboarding",
            index=models.Index(
                fields=["session_id"], name="company_onb_session_ae85a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyintegration",
            index=models.Index(
                fields=["company", "status"], name="company_int_company_242504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyintegration",
            index=models.Index(
                fields=["integration_type"], name="company_int_integra_65d083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyintegration",
            index=models.Index(
                fields=["is_enabled", "status"], name="company_int_is_enab_4e4408_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyintegration",
            unique_together={("company", "integration_type", "name")},
        ),
        migrations.AddIndex(
            model_name="usercompanymembership",
            index=models.Index(
                fields=["company", "is_active"], name="user_compan_company_f7294e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercompanymembership",
            index=models.Index(
                fields=["user", "is_active"], name="user_compan_user_id_3fac59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercompanymembership",
            index=models.Index(fields=["role"], name="user_compan_role_94bfeb_idx"),
        ),
        migrations.AddIndex(
            model_name="usercompanymembership",
            index=models.Index(
                fields=["is_owner"], name="user_compan_is_owne_ce9126_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercompanymembership",
            unique_together={("user", "company")},
        ),
    ]
