# Generated by Django 5.2 on 2025-09-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_create_security_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmenttype",
            name="company",
            field=models.ForeignKey(
                help_text="Company that owns this employment type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employment_types",
                to="api.securitycompany",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="company",
            field=models.OneToOneField(
                help_text="Company that owns these settings",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="api.securitycompany",
            ),
        ),
        migrations.AlterField(
            model_name="employmenttype",
            name="name",
            field=models.CharField(
                help_text="Employment type name (e.g., 'Contract Workers', 'Temporary Staff')",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employmenttype",
            unique_together={("company", "name")},
        ),
    ]
