# Generated by Django 5.2 on 2025-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_add_company_fields_to_settings_and_employment_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitycompany",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier for company recruitment pages",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
