# Generated by Django 5.2 on 2025-09-28 00:30

from django.db import migrations
from django.utils.text import slugify


def populate_company_slugs(apps, schema_editor):
    """
    Populate slug field for existing companies.
    Create URL-friendly slugs based on company names.
    """
    SecurityCompany = apps.get_model('api', 'SecurityCompany')

    for company in SecurityCompany.objects.filter(slug__isnull=True):
        # Create base slug from company name
        base_slug = slugify(company.name)

        # Ensure uniqueness by adding numbers if needed
        slug = base_slug
        counter = 1

        while SecurityCompany.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        company.slug = slug
        company.save()


def reverse_populate_company_slugs(apps, schema_editor):
    """
    Reverse operation - clear slug field.
    """
    SecurityCompany = apps.get_model('api', 'SecurityCompany')
    SecurityCompany.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_add_company_slug_field"),
    ]

    operations = [
        migrations.RunPython(populate_company_slugs, reverse_populate_company_slugs),
    ]
