# Generated by Django 5.2 on 2025-10-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_populate_company_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_last_changed",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last password change", null=True
            ),
        ),
    ]
