# Generated by Django 5.2 on 2025-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_add_password_last_changed_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="description",
            field=models.TextField(
                blank=True, help_text="venue description", null=True
            ),
        ),
    ]
