# Generated by Django 5.0.1 on 2025-10-26 02:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_venue_description_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_reminders_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable shift reminder notifications",
                    ),
                ),
                (
                    "advance_reminder_hours",
                    models.IntegerField(
                        default=3,
                        help_text="Hours before shift to send advance reminder (1-24)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "final_reminder_minutes",
                    models.IntegerField(
                        default=45,
                        help_text="Minutes before shift to send final reminder (15-180)",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "exchange_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable shift exchange notifications",
                    ),
                ),
                (
                    "exchange_request_received",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when someone requests to exchange shifts",
                    ),
                ),
                (
                    "exchange_request_accepted",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when your exchange request is accepted",
                    ),
                ),
                (
                    "exchange_request_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when manager approves your exchange",
                    ),
                ),
                (
                    "available_shifts_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable available shift notifications",
                    ),
                ),
                (
                    "new_available_shift",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when new shifts become available to claim",
                    ),
                ),
                (
                    "incident_alerts_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable critical incident alerts",
                    ),
                ),
                (
                    "sync_notifications_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable/disable sync status notifications",
                    ),
                ),
                (
                    "sync_errors_only",
                    models.BooleanField(
                        default=True,
                        help_text="Only notify on sync errors, not successful syncs",
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable quiet hours (no notifications during these times)",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for quiet hours (e.g., 22:00)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time for quiet hours (e.g., 07:00)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="SNSDeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Expo push token for the device",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        help_text="Device platform (iOS or Android)",
                        max_length=10,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier", max_length=255
                    ),
                ),
                (
                    "endpoint_arn",
                    models.CharField(
                        blank=True,
                        help_text="AWS SNS Platform Endpoint ARN (optional, for future SNS integration)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device token is active and should receive notifications",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a notification was sent to this device",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Push Token",
                "verbose_name_plural": "Device Push Tokens",
                "db_table": "sns_device_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="sns_device__user_id_a836bb_idx",
                    ),
                    models.Index(fields=["token"], name="sns_device__token_179eb7_idx"),
                ],
            },
        ),
    ]
