# Generated by Django 5.0.1 on 2025-12-09 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_notificationpreferences_snsdevicetoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentreport",
            options={"ordering": ["-occurred_at", "-incident_time"]},
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="ambulance_called",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("security_breach", "Security Breach"),
                    ("medical_emergency", "Medical Emergency"),
                    ("fire_alarm", "Fire Alarm"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("property_damage", "Property Damage"),
                    ("assault", "Assault"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="location_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="occurred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="persons_involved",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="police_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="police_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="reported_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("resolved", "Resolved"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="videos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="voice_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="witnesses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="actions_taken",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["venue", "occurred_at"], name="incident_re_venue_i_d60ef2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["incident_type", "status"],
                name="incident_re_inciden_62e8b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["status", "occurred_at"], name="incident_re_status_5f17aa_idx"
            ),
        ),
    ]
