# Generated by Django 5.0.1 on 2025-12-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_add_incident_report_mobile_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentreport",
            options={"ordering": ["-incident_time"]},
        ),
        migrations.RemoveIndex(
            model_name="incidentreport",
            name="incident_re_venue_i_d60ef2_idx",
        ),
        migrations.RemoveIndex(
            model_name="incidentreport",
            name="incident_re_inciden_62e8b5_idx",
        ),
        migrations.RemoveIndex(
            model_name="incidentreport",
            name="incident_re_status_5f17aa_idx",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="ambulance_called",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="incident_type",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="location_description",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="occurred_at",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="persons_involved",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="police_notified",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="police_reference",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="reported_at",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="status",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="title",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="videos",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="voice_note",
        ),
        migrations.RemoveField(
            model_name="incidentreport",
            name="witnesses",
        ),
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Account locked until this timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_failed_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last failed login attempt",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="actions_taken",
            field=models.TextField(),
        ),
    ]
