# Generated by Django 5.0.1 on 2026-01-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_fix_users_without_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="auto_approve_shift_exchanges",
            field=models.BooleanField(
                default=True,
                help_text="Automatically approve shift exchanges when no conflicts exist",
            ),
        ),
    ]
