# Generated by Django 5.0.1 on 2026-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_add_auto_approve_shift_exchanges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sialicense",
            name="document_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
