# Generated by Django 5.2 on 2026-01-09
# Migration to add venue location enforcement settings

from django.db import migrations, models


def migrate_legacy_venues(apps, schema_editor):
    """
    Set all existing venues to 'notify' mode to prevent blocking staff.
    Increase radius to 150m for existing unverified venues to be safe.
    """
    Venue = apps.get_model('api', 'Venue')
    Venue.objects.all().update(
        location_enforcement='notify',
        is_location_verified=False,
        check_radius=150
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse the data migration - reset check_radius to default.
    """
    Venue = apps.get_model('api', 'Venue')
    Venue.objects.all().update(check_radius=50)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_make_document_url_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location_enforcement',
            field=models.CharField(
                choices=[
                    ('block', 'Strict: Block check-in if outside radius'),
                    ('notify', 'Soft: Allow check-in but notify manager'),
                    ('none', 'Disabled: No location verification'),
                ],
                default='block',
                max_length=10,
                help_text='How strictly to enforce location verification for check-ins'
            ),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_location_verified',
            field=models.BooleanField(
                default=False,
                help_text='True only if admin has visually confirmed the pin on the map'
            ),
        ),
        migrations.AlterField(
            model_name='venue',
            name='check_radius',
            field=models.IntegerField(
                default=100,
                help_text='Radius in meters for location verification (min 100m recommended for GPS accuracy)'
            ),
        ),
        # Run the data migration to protect existing venues
        migrations.RunPython(migrate_legacy_venues, reverse_migration),
    ]
