# Generated by Django 5.0.1 on 2026-01-10 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_add_venue_enforcement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="is_location_verified",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="location_enforcement",
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="shift",
            field=models.ForeignKey(
                help_text="Each shift can only be invoiced once",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items",
                to="api.shift",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="check_radius",
            field=models.IntegerField(
                default=50, help_text="Radius in meters for location verification"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                fields=("shift",),
                name="unique_shift_per_invoice_item",
                violation_error_message="This shift has already been added to an invoice.",
            ),
        ),
    ]
