# Generated by Django 5.0.1 on 2026-01-17 21:15

from django.db import migrations


def update_venue_check_radius(apps, schema_editor):
    """Update all venues with check_radius < 100 to 100m."""
    Venue = apps.get_model('api', 'Venue')
    Venue.objects.filter(check_radius__lt=100).update(check_radius=100)


def reverse_update(apps, schema_editor):
    """Reverse migration - set back to 50m."""
    Venue = apps.get_model('api', 'Venue')
    Venue.objects.filter(check_radius=100).update(check_radius=50)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_add_unique_shift_constraint_invoice_item"),
    ]

    operations = [
        migrations.RunPython(update_venue_check_radius, reverse_update),
    ]
