# Generated by Django 5.0.1 on 2026-01-19 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_add_user_presence_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "System/Shift Generated"),
                    ("admin", "Admin Generated"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="UserPresenceStatus",
        ),
    ]
