# Generated by Django 5.0.1 on 2026-01-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_add_invoice_source_and_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="last_recalculated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time invoice was recalculated from shift adjustments",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Increments on each recalculation"
            ),
        ),
        migrations.CreateModel(
            name="TimeAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_check_in_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original check-in time before adjustment",
                        null=True,
                    ),
                ),
                (
                    "original_check_out_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original check-out time before adjustment",
                        null=True,
                    ),
                ),
                (
                    "original_actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original actual hours worked",
                        max_digits=5,
                    ),
                ),
                (
                    "adjusted_check_in_time",
                    models.DateTimeField(
                        blank=True, help_text="Corrected check-in time", null=True
                    ),
                ),
                (
                    "adjusted_check_out_time",
                    models.DateTimeField(
                        blank=True, help_text="Corrected check-out time", null=True
                    ),
                ),
                (
                    "adjusted_actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Corrected actual hours worked",
                        max_digits=5,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Explanation for the adjustment (required)"
                    ),
                ),
                (
                    "manager_signature",
                    models.TextField(help_text="Base64 encoded signature image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_adjustments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_adjustments",
                        to="api.shift",
                    ),
                ),
            ],
            options={
                "db_table": "time_adjustments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shift", "-created_at"],
                        name="time_adjust_shift_i_040102_idx",
                    )
                ],
            },
        ),
    ]
