# Generated by Django 5.0.1 on 2026-01-22 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_shift_group_and_performed_by_to_checks'),
        ('leave_management', '0006_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Holiday name (e.g., 'Christmas Day')", max_length=100)),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Holiday',
                'verbose_name_plural': 'Bank Holidays',
                'db_table': 'bank_holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ContractorUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of unavailability')),
                ('end_date', models.DateField(help_text='Last day of unavailability')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for unavailability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contractor Unavailability',
                'verbose_name_plural': 'Contractor Unavailability Periods',
                'db_table': 'contractor_unavailability',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeaveDailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rate for paid leave calculation', max_digits=10)),
                ('effective_from', models.DateField(help_text='Date from which this rate is effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Leave Daily Rate',
                'verbose_name_plural': 'Staff Leave Daily Rates',
                'db_table': 'staff_leave_daily_rates',
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['date', 'item_type']},
        ),
        migrations.RemoveConstraint(
            model_name='invoiceitem',
            name='unique_shift_per_invoice_item',
        ),
        migrations.AddField(
            model_name='employmenttype',
            name='employment_category',
            field=models.CharField(choices=[('permanent', 'Permanent Employee'), ('contractor', 'Contractor'), ('temporary', 'Temporary Staff')], default='contractor', help_text='Category determining leave/availability behavior: permanent gets paid leave, contractors mark availability', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Days for leave items (e.g., 1 for full day, 0.5 for half day)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, help_text="Description for the line item (e.g., 'Bank Holiday: Christmas Day')", max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('shift', 'Shift Work'), ('bank_holiday', 'Bank Holiday Pay'), ('annual_leave', 'Annual Leave Pay')], default='shift', help_text='Type of invoice item', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='leave_request',
            field=models.ForeignKey(blank=True, help_text='Leave request for annual leave items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='leave_management.leaverequest'),
        ),
        migrations.AlterField(
            model_name='capacitycheck',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed this check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fireexitcheck',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed this check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked for shift items (null for leave items)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Hourly rate for shifts or daily rate for leave', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift for shift items (null for leave items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.shift'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Venue for shift items (null for leave items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.venue'),
        ),
        migrations.AlterField(
            model_name='toiletcheck',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed this check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankholiday',
            name='company',
            field=models.ForeignKey(help_text='Company this holiday belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bank_holidays', to='api.securitycompany'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='bank_holiday',
            field=models.ForeignKey(blank=True, help_text='Bank holiday for bank holiday pay items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.bankholiday'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('shift__isnull', False)), fields=('shift',), name='unique_shift_per_invoice_item', violation_error_message='This shift has already been added to an invoice.'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_holiday__isnull', False)), fields=('invoice', 'bank_holiday'), name='unique_bank_holiday_per_invoice', violation_error_message='This bank holiday has already been added to this invoice.'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('leave_request__isnull', False)), fields=('invoice', 'leave_request', 'date'), name='unique_leave_request_date_per_invoice', violation_error_message='This leave day has already been added to this invoice.'),
        ),
        migrations.AddField(
            model_name='contractorunavailability',
            name='company',
            field=models.ForeignKey(help_text='Company this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contractor_unavailability', to='api.securitycompany'),
        ),
        migrations.AddField(
            model_name='contractorunavailability',
            name='staff_user',
            field=models.ForeignKey(help_text='Contractor who is marking unavailability', on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleavedailyrate',
            name='company',
            field=models.ForeignKey(help_text='Company this rate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_leave_rates', to='api.securitycompany'),
        ),
        migrations.AddField(
            model_name='staffleavedailyrate',
            name='staff_user',
            field=models.OneToOneField(help_text='Staff member this rate applies to', on_delete=django.db.models.deletion.CASCADE, related_name='leave_daily_rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleavedailyrate',
            name='updated_by',
            field=models.ForeignKey(help_text='Admin who last updated this rate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bankholiday',
            index=models.Index(fields=['company', 'date', 'is_active'], name='bank_holida_company_6e3b35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankholiday',
            unique_together={('company', 'date')},
        ),
        migrations.AddIndex(
            model_name='contractorunavailability',
            index=models.Index(fields=['staff_user', 'start_date', 'end_date'], name='contractor__staff_u_656182_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorunavailability',
            index=models.Index(fields=['company', 'start_date'], name='contractor__company_cf5502_idx'),
        ),
        migrations.AddIndex(
            model_name='staffleavedailyrate',
            index=models.Index(fields=['company', 'staff_user'], name='staff_leave_company_9cb2c4_idx'),
        ),
    ]
