# Generated by Django 5.0.1 on 2026-01-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_update_venue_check_radius"),
        ("api", "0047_bankholiday_contractorunavailability_and_more"),
    ]

    operations = []
