# Generated by Django 5.0.1 on 2026-01-26 01:27

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing NotificationPreferences records."""
    NotificationPreferences = apps.get_model('api', 'NotificationPreferences')
    for pref in NotificationPreferences.objects.all():
        pref.email_unsubscribe_token = uuid.uuid4()
        pref.save(update_fields=['email_unsubscribe_token'])


def reverse_generate_unique_uuids(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_bankholiday_contractorunavailability_and_more"),
    ]

    operations = [
        # Add boolean fields first (these are straightforward)
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_approval_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Receive email when shifts or claims are approved",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_exchange_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Receive email for shift exchange requests and status updates",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True, help_text="Master toggle for all email notifications"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_open_shift_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Receive email when open shifts are available to claim",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_shift_assignments",
            field=models.BooleanField(
                default=True, help_text="Receive email when assigned to a shift"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_shift_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Receive email reminders before shifts (default off to reduce email volume)",
            ),
        ),
        # Step 1: Add UUID field without unique constraint
        migrations.AddField(
            model_name="notificationpreferences",
            name="email_unsubscribe_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Token for one-click email unsubscribe links",
                null=True,
            ),
        ),
        # Step 2: Generate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_uuids, reverse_generate_unique_uuids),
        # Step 3: Alter field to add unique constraint and remove null
        migrations.AlterField(
            model_name="notificationpreferences",
            name="email_unsubscribe_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Token for one-click email unsubscribe links",
                unique=True,
            ),
        ),
    ]
