# Generated by Django 5.0.1 on 2026-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_0048_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='check_radius',
            field=models.IntegerField(default=100, help_text='Radius in meters for location verification'),
        ),
    ]
