# Generated by Django 5.0.1 on 2026-02-11 15:59

from django.db import migrations


def fix_existing_no_shows(apps, schema_editor):
    """Retroactively set no_show status on force-completed shifts with 0 hours and no check-in."""
    Shift = apps.get_model('api', 'Shift')
    Shift.objects.filter(
        status='completed',
        actual_hours_worked=0,
        check_in_time__isnull=True,
    ).update(status='no_show')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_no_show_status'),
    ]

    operations = [
        migrations.RunPython(fix_existing_no_shows, migrations.RunPython.noop),
    ]
