# Generated by Django 5.0.1 on 2026-02-27 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_fix_existing_no_shows"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="contracted_weekly_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Contracted weekly hours. Null = full-time (no contractual cap).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="employment_type_effective_from",
            field=models.DateField(
                blank=True,
                help_text="Date when the current employment type became effective.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complianceviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("daily_overtime", "Daily Hours Exceeded"),
                    ("weekly_overtime", "Weekly Hours Exceeded"),
                    ("consecutive_days", "Too Many Consecutive Days"),
                    ("insufficient_rest", "Insufficient Rest Between Shifts"),
                    ("missing_break", "Required Break Not Taken"),
                    ("late_checkin", "Late Check-in"),
                    ("early_checkout", "Early Check-out"),
                    ("location_violation", "Location Compliance Violation"),
                    ("unauthorized_overtime", "Unauthorized Overtime"),
                    ("shift_abandonment", "Shift Abandonment"),
                    ("documentation_missing", "Missing Required Documentation"),
                    ("contracted_hours_exceeded", "Contracted Hours Exceeded"),
                    ("custom", "Custom Violation Type"),
                ],
                help_text="Type of compliance violation",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EmploymentTypeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date when the change takes effect"),
                ),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employment_type_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_type_changes",
                        to="api.securitycompany",
                    ),
                ),
                (
                    "new_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="New employment type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.employmenttype",
                    ),
                ),
                (
                    "old_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous employment type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.employmenttype",
                    ),
                ),
                (
                    "staff_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_type_changes",
                        to="api.staffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "employment_type_changes",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["staff_profile", "-changed_at"],
                        name="employment__staff_p_826467_idx",
                    ),
                    models.Index(
                        fields=["company", "-changed_at"],
                        name="employment__company_45b368_idx",
                    ),
                ],
            },
        ),
    ]
