# Generated by Django 5.0.1 on 2026-04-01 23:54

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_contracted_hours_and_employment_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='contracted_weekly_hours',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='employment_type_effective_from',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='sort_code',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complianceviolation',
            name='violation_type',
            field=models.CharField(choices=[('daily_overtime', 'Daily Hours Exceeded'), ('weekly_overtime', 'Weekly Hours Exceeded'), ('consecutive_days', 'Too Many Consecutive Days'), ('insufficient_rest', 'Insufficient Rest Between Shifts'), ('missing_break', 'Required Break Not Taken'), ('late_checkin', 'Late Check-in'), ('early_checkout', 'Early Check-out'), ('location_violation', 'Location Compliance Violation'), ('unauthorized_overtime', 'Unauthorized Overtime'), ('shift_abandonment', 'Shift Abandonment'), ('documentation_missing', 'Missing Required Documentation'), ('custom', 'Custom Violation Type')], help_text='Type of compliance violation', max_length=30),
        ),
        migrations.DeleteModel(
            name='EmploymentTypeChange',
        ),
    ]
