# Generated by Django 5.0.1 on 2026-04-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_notification_and_client_billing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clientinvoice",
            new_name="client_invo_company_c104ad_idx",
            old_name="ci_company_status_idx",
        ),
        migrations.RenameIndex(
            model_name="clientinvoice",
            new_name="client_invo_venue_i_293fd6_idx",
            old_name="ci_venue_date_idx",
        ),
        migrations.RenameIndex(
            model_name="clientinvoice",
            new_name="client_invo_invoice_537051_idx",
            old_name="ci_number_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_c4e471_idx",
            old_name="notif_user_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_63f199_idx",
            old_name="notif_user_type_idx",
        ),
        migrations.AddField(
            model_name="shift",
            name="bill_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly bill rate charged to client for this shift",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether this shift is visible to staff (draft vs published)",
            ),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="client_name",
            field=models.CharField(
                help_text="Client/venue name at time of invoicing", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="company",
            field=models.ForeignKey(
                help_text="Security company issuing the invoice",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoices",
                to="api.securitycompany",
            ),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="end_date",
            field=models.DateField(help_text="End of billing period"),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="start_date",
            field=models.DateField(help_text="Start of billing period"),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Tax/VAT rate percentage (default 20% UK VAT)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="venue",
            field=models.ForeignKey(
                help_text="Venue/client being billed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoices",
                to="api.venue",
            ),
        ),
        migrations.AlterField(
            model_name="clientinvoiceitem",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Client billing rate per hour (distinct from staff pay rate)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="clientinvoiceitem",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Source shift (if generated from shifts)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_invoice_items",
                to="api.shift",
            ),
        ),
    ]
