# Generated by Django 5.0.1 on 2026-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_add_shift_is_published_and_bill_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When account deletion was requested. Hard delete occurs 30 days after this date.",
                null=True,
            ),
        ),
    ]
