# Generated by Django 5.2 on 2026-04-29 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_add_deletion_scheduled_at_to_user"),
        ("leave_management", "0006_systemconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_code",
                    models.CharField(
                        help_text="ISO week code, e.g. W17-2026",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human label, e.g. 'Week 17 · w/c Mon 20 Apr 2026'",
                        max_length=120,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Monday of the run period"),
                ),
                ("period_end", models.DateField(help_text="Sunday of the run period")),
                (
                    "process_date",
                    models.DateField(
                        help_text="Day the run was processed (typically the following Monday)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("invoice_count", models.IntegerField(default=0)),
                ("line_item_count", models.IntegerField(default=0)),
                (
                    "hours_billed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "prev_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("time_adjustments", models.IntegerField(default=0)),
                ("sia_blocks", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payroll_runs",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement_number", models.CharField(max_length=50, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                (
                    "sent_to_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frozen list of invoice rows: [{invoice_number, issued, due, total, paid_total, balance}, …]",
                    ),
                ),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "statements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatementInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "statement_invoices",
                "ordering": ["sort_order", "invoice__issued_date"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="invoiceitem",
            name="unique_shift_per_invoice_item",
        ),
        migrations.AddField(
            model_name="clientinvoice",
            name="reject_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Display invoice number, e.g. PAY-2026-00481",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issued_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reject_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="clientinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("shift", "Shift Work"),
                    ("overtime_1", "Overtime tier 1 (1.5x)"),
                    ("overtime_2", "Overtime tier 2 (2x)"),
                    ("bank_holiday", "Bank Holiday Pay"),
                    ("annual_leave", "Annual Leave Pay"),
                    ("special", "Special Event"),
                ],
                default="shift",
                help_text="Type of invoice item",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shift__isnull", False)),
                fields=("invoice", "shift", "item_type"),
                name="unique_shift_invoice_item_type",
                violation_error_message="This shift has already been added to this invoice for this item type.",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_runs",
                to="api.securitycompany",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_runs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_invoices",
                to="api.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statements",
                to="api.securitycompany",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statements_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statements",
                to="api.venue",
            ),
        ),
        migrations.AddField(
            model_name="statementinvoice",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statement_invoices",
                to="api.clientinvoice",
            ),
        ),
        migrations.AddField(
            model_name="statementinvoice",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statement_invoices",
                to="api.statement",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="invoices",
            field=models.ManyToManyField(
                related_name="statements",
                through="api.StatementInvoice",
                to="api.clientinvoice",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["company", "-period_start"],
                name="payroll_run_company_3f4120_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["run_code"], name="payroll_run_run_cod_4897b4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("company", "period_start", "period_end"),
                name="unique_payrollrun_per_company_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="statementinvoice",
            constraint=models.UniqueConstraint(
                fields=("statement", "invoice"), name="unique_statement_invoice"
            ),
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(
                fields=["company", "-created_at"], name="statements_company_fd30a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(
                fields=["venue", "period_start"], name="statements_venue_i_7c6e85_idx"
            ),
        ),
    ]
