# Generated by Django 5.2 on 2026-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_billing_payroll_alignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollrun",
            name="run_code",
            field=models.CharField(
                help_text="ISO week code, e.g. W17-2026 — unique per company, not global",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("company", "run_code"),
                name="unique_payrollrun_code_per_company",
            ),
        ),
    ]
