# Generated by Django 5.2 on 2026-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_payroll_run_code_per_company"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payrollrun",
            name="unique_payrollrun_per_company_period",
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="cycle",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="weekly",
                help_text="Pay cycle this run covers — controls which staff are included.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="pay_frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="weekly",
                help_text="How often this officer is paid; selects which payroll cycle (weekly W-runs vs monthly M-runs) generates their invoices.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="label",
            field=models.CharField(
                help_text="Human label, e.g. 'Week 17 · w/c Mon 20 Apr 2026' or 'April 2026'",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="period_end",
            field=models.DateField(help_text="Last day of the run period (inclusive)"),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="period_start",
            field=models.DateField(help_text="First day of the run period (inclusive)"),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="process_date",
            field=models.DateField(
                help_text="Day the run is processed (Monday after for weekly, 1st of next month for monthly)"
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="run_code",
            field=models.CharField(
                help_text="Run code: W{week}-{year} for weekly, M{month}-{year} for monthly. Unique per (company, cycle).",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("company", "cycle", "period_start", "period_end"),
                name="unique_payrollrun_per_company_period",
            ),
        ),
    ]
