# Generated by Django 5.2 on 2026-04-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_remove_payrollrun_unique_payrollrun_per_company_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinvoice",
            name="superseded_by",
            field=models.OneToOneField(
                blank=True,
                help_text="When set, this invoice has been replaced by a re-issued draft. Display as 'Resolved' instead of 'Rejected' so it falls out of the manager's open work queue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="api.clientinvoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="superseded_by",
            field=models.OneToOneField(
                blank=True,
                help_text="When set, this invoice has been replaced by a re-issued draft. Display as 'Resolved' instead of 'Rejected' so it falls out of the manager's open work queue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="api.invoice",
            ),
        ),
    ]
