# Generated by Django 5.2 on 2026-05-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_clientinvoice_superseded_by_invoice_superseded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinvoice",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, this invoice has been replaced by another invoice. Many-to-one: a single replacement invoice can supersede multiple draft auto-invoices in the hybrid flow, or a single rejected invoice can be superseded by its reissue. Display as 'Resolved' instead of 'Rejected' so it falls out of the manager's open work queue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="api.clientinvoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, this invoice has been replaced by another invoice. Many-to-one: a single replacement invoice can supersede multiple draft auto-invoices in the hybrid flow, or a single rejected invoice can be superseded by its reissue. Display as 'Resolved' instead of 'Rejected' so it falls out of the manager's open work queue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="api.invoice",
            ),
        ),
    ]
