# Generated by Django 5.2 on 2026-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_alter_clientinvoice_superseded_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
