# Generated by Django 5.2 on 2026-05-09 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_recruitmentapplication_drop_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="capacity_check_interval_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="How often (minutes) staff must log a capacity count when capacity monitoring is required",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="capacity_warning_threshold_pct",
            field=models.PositiveSmallIntegerField(
                default=80,
                help_text="Percentage of venue capacity at which the UI should highlight 'approaching capacity'",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("shift_assigned", "Shift Assigned"),
                    ("shift_removed", "Shift Removed"),
                    ("shift_updated", "Shift Updated"),
                    ("shift_approved", "Shift Approved"),
                    ("shift_rejected", "Shift Rejected"),
                    ("open_shift", "Open Shift Available"),
                    ("exchange_request", "Exchange Request"),
                    ("exchange_approved", "Exchange Approved"),
                    ("exchange_rejected", "Exchange Rejected"),
                    ("leave_approved", "Leave Approved"),
                    ("leave_rejected", "Leave Rejected"),
                    ("compliance_alert", "Compliance Alert"),
                    ("sia_expiry", "SIA License Expiry"),
                    ("invoice_ready", "Invoice Ready"),
                    ("invoice_paid", "Invoice Paid"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CapacityLogbookSignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_group",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "closed_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Typed name of the venue's duty manager (blank if overridden)",
                        max_length=120,
                    ),
                ),
                (
                    "closed_by_role",
                    models.CharField(
                        blank=True,
                        help_text="Role/title of the signer, e.g. 'Duty Manager'",
                        max_length=80,
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64-encoded signature image (blank if overridden)",
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "override_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason why no signature was captured (e.g. 'Duty manager left early')",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "total_checks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Snapshot: number of CapacityCheck rows in the shift_group at signoff time",
                    ),
                ),
                (
                    "total_missed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Snapshot: number of CapacityCheckSlotMiss rows in the shift_group at signoff time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by_staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Guard staff member who submitted this signoff",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capacity_signoffs_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_signoffs",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "capacity_logbook_signoffs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CapacityCheckSlotMiss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_group", models.CharField(db_index=True, max_length=50)),
                (
                    "expected_at",
                    models.DateTimeField(
                        help_text="Start of the slot window that was missed"
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_reason", models.TextField(blank=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capacity_misses_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_misses",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "db_table": "capacity_check_slot_misses",
                "ordering": ["-expected_at"],
                "indexes": [
                    models.Index(
                        fields=["shift_group", "expected_at"],
                        name="capacity_ch_shift_g_fc0aa2_idx",
                    )
                ],
                "unique_together": {("shift_group", "expected_at")},
            },
        ),
    ]
