# Generated by Django 5.2 on 2026-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_venue_capacity_check_interval_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacitylogbooksignoff",
            name="auto_closed",
            field=models.BooleanField(
                default=False,
                help_text="True when the signoff was created by the system on auto-checkout (no staff input). Distinguishes audit-trail noise from a deliberate staff override.",
            ),
        ),
    ]
