# Generated by Django 5.2 on 2026-09-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_capacitylogbooksignoff_auto_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sialicense",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sialicense",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Approver who moved this licence to valid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_sia_licenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("role_change", "Role Change"),
                    ("security_roles_change", "Security Roles Change"),
                    ("status_change", "Status Change"),
                    ("geofence_change", "Geofence Change"),
                    ("export", "Data Export"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                ],
                max_length=50,
            ),
        ),
    ]
