# Generated by Django 5.2 on 2026-09-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_sia_licence_verification_and_audit_actions"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("superseded_by__isnull", True)),
                fields=("staff_user", "start_date", "end_date"),
                name="uniq_live_invoice_per_staff_period",
            ),
        ),
    ]
