# Generated by Django 5.2 on 2026-09-07 22:09

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_unique_live_invoice_per_staff_period"),
    ]

    operations = [
        # The overlap constraint below is a GiST exclusion over a scalar
        # (staff_user) and a range (the shift window). GiST cannot index the
        # scalar without btree_gist, so the extension has to exist before the
        # constraint is built. Requires a superuser on first run; on Render the
        # migration user owns the database, so this is a no-op after the first
        # deploy.
        BtreeGistExtension(),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["start_time"], name="shift_start_time_idx"),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["staff_user", "start_time"], name="shift_staff_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["status", "is_published"], name="shift_status_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["venue", "start_time"], name="shift_venue_start_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("end_time__isnull", False),
                    ("staff_user__isnull", False),
                    models.Q(("status__in", ["cancelled", "rejected"]), _negated=True),
                ),
                expressions=[
                    ("staff_user", "="),
                    (
                        models.Func(
                            "start_time",
                            "end_time",
                            models.Value("[)"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="shift_no_overlapping_assignment",
            ),
        ),
    ]
