# Generated by Django 5.2 on 2026-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_shift_indexes_and_overlap_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="payable_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hours this shift is actually paid for: scheduled minus break, or an admin's TimeAdjustment, or capped actual hours on auto-checkout. Persisted so the weekly overtime accumulator and the invoice header can read the same quantity the payment does — see OT_BASIS_ALIGNED.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
