# Generated by Django 5.2 on 2026-09-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_shift_payable_hours"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="openshiftrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("original_shift",),
                name="uniq_open_request_per_shift",
            ),
        ),
    ]
