# Generated by Django 5.2 on 2026-09-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_unique_open_shift_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="needs_attendance_review",
            field=models.BooleanField(
                default=False,
                help_text="An offline replay recorded a time the server could not verify. Surfaces in the manager attendance-exceptions queue.",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="reported_check_in_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Client-asserted check-in time from an offline replay. Never used for pay; for manager reconciliation only.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="reported_check_out_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Client-asserted check-out time from an offline replay.",
                null=True,
            ),
        ),
    ]
