# Generated by Django 5.2.11 on 2026-09-07 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_offline_attendance_replay"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacitycheck",
            name="baseline_occupancy",
            field=models.IntegerField(
                default=0,
                help_text="Occupancy banked from before the current clicker segment. Stored per row so the logbook reconstructs without replaying every earlier check.",
            ),
        ),
        migrations.AddField(
            model_name="capacitycheck",
            name="count_in",
            field=models.IntegerField(
                blank=True,
                help_text="Clicker's running 'in' total at the time of this check.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="capacitycheck",
            name="count_out",
            field=models.IntegerField(
                blank=True,
                help_text="Clicker's running 'out' total at the time of this check.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="capacitycheck",
            name="counter_reset",
            field=models.BooleanField(
                default=False,
                help_text="This reading is lower than the previous one, so the clicker was reset. Occupancy carries forward from before the reset.",
            ),
        ),
    ]
