# Generated by Django 5.2.11 on 2026-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_capacity_check_in_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinvoiceitem",
            name="needs_rate",
            field=models.BooleanField(
                default=False,
                help_text="The source shift had no bill rate, so this line is priced at 0 and the invoice cannot be issued until a manager sets one.",
            ),
        ),
    ]
