# Generated by Django 5.2.11 on 2026-09-19 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_client_invoice_item_needs_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinvoice",
            name="venue",
            field=models.ForeignKey(
                help_text="Venue/client being billed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_invoices",
                to="api.venue",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="staff_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift for shift items (null for leave items)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="api.shift",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="staff_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="api.venue",
            ),
        ),
        migrations.AlterField(
            model_name="timeadjustment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_adjustments",
                to="api.shift",
            ),
        ),
    ]
