# Generated by Django 5.2.11 on 2026-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0075 on the merge to main: 0075 was taken by the
        # profile-photo keys migration, and two leaves abort the Render build.
        ("api", "0075_profile_photo_storage_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinvoiceitem",
            name="needs_rate",
            field=models.BooleanField(
                default=False,
                help_text="The source shift had no bill rate, so this line is priced at 0 and the invoice cannot be issued until a manager sets one.",
            ),
        ),
    ]
