# Generated by Django 5.2.11 on 2026-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_protect_pay_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_review_account",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="App Store review demo account. Exempt from geofence, login lockout and auto no-show.",
            ),
        ),
    ]
