# Generated by Django 5.2.11 on 2026-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0079_relax_orphan_incident_report_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="actions_taken",
            field=models.TextField(blank=True, default=""),
        ),
    ]
