# Generated by Django 5.2.11 on 2026-09-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_incident_actions_taken_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacitycheck",
            name="baseline_occupancy",
            field=models.IntegerField(
                default=0,
                help_text="Occupancy recorded before in/out readings began (a headcount logged the old way). Stored per row so the logbook reconstructs without replaying every earlier check.",
            ),
        ),
        migrations.AlterField(
            model_name="capacitycheck",
            name="counter_reset",
            field=models.BooleanField(
                default=False,
                help_text="This reading is lower than the previous one. It is taken as the true figure; nothing is carried forward.",
            ),
        ),
    ]
