"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError('DJANGO_SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,172.16.32.165,10.0.4.21,10.0.4.27,192.168.0.127,192.168.1.82').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django_filters',
    # Django Channels
    'channels',
    # Celery apps
    'django_celery_beat',
    'django_celery_results',
    # Project apps
    'api',
    'shifts',
    'finance_integrations',
    'leave_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.tenant_middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Exempt API endpoints from CSRF (mobile app uses JWT tokens, not cookies)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://10.0.4.21:8081',
    'http://10.0.4.21:19000',
    'http://10.0.4.27:8081',
    'http://10.0.4.27:19000',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'security_management'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Asyncpg database configuration
ASYNCPG_DATABASE = {
    'database': os.getenv('DB_NAME', 'security_management'),
    'user': os.getenv('DB_USER', 'postgres'),
    'password': os.getenv('DB_PASSWORD', 'postgres'),
    'host': os.getenv('DB_HOST', 'localhost'),
    'port': int(os.getenv('DB_PORT', '5432')),
    'command_timeout': 60,  # timeout for operations in seconds
    'min_size': 10,  # minimum pool size
    'max_size': 20,  # maximum pool size
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing Configuration
# Using bcrypt for industry-standard password security
# Fallback to PBKDF2 for backward compatibility with existing users
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # Primary: bcrypt with SHA256
    'django.contrib.auth.hashers.BCryptPasswordHasher',        # Fallback: standard bcrypt
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',        # Fallback: existing users (PBKDF2)
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',    # Legacy support
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings - Secure configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in debug mode
CORS_ALLOW_CREDENTIALS = True

# Production CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "https://localhost:3001",
    "https://127.0.0.1:3001",
    # Mobile app development
    "http://10.0.4.21:8081",
    "http://10.0.4.21:8082",
    "http://10.0.4.21:19000",
    "http://10.0.4.21:19001",
    "http://10.0.4.27:8081",
    "http://10.0.4.27:8082",
    "http://10.0.4.27:19000",
    "http://10.0.4.27:19001",
]

# Add any additional production origins from environment
additional_origins = os.getenv('CORS_ADDITIONAL_ORIGINS')
if additional_origins:
    CORS_ALLOWED_ORIGINS.extend(additional_origins.split(','))

# Finance Integrations OAuth Settings
FINANCE_OAUTH_SETTINGS = {
    'xero': {
        'client_id': os.environ.get('XERO_CLIENT_ID', ''),
        'client_secret': os.environ.get('XERO_CLIENT_SECRET', ''),
        'scope': 'accounting.transactions accounting.contacts.read accounting.settings payroll.employees payroll.payruns payroll.settings files',
        'redirect_uri': os.environ.get('XERO_REDIRECT_URI', 'http://localhost:3000/admin/finance-integrations/oauth-callback'),
    },
    'quickbooks': {
        'client_id': os.environ.get('QUICKBOOKS_CLIENT_ID', ''),
        'client_secret': os.environ.get('QUICKBOOKS_CLIENT_SECRET', ''),
        'scope': 'com.intuit.quickbooks.accounting',
        'redirect_uri': os.environ.get('QUICKBOOKS_REDIRECT_URI', 'http://localhost:3000/admin/finance-integrations/oauth-callback'),
        'discovery_document': 'https://appcenter.intuit.com/connect/oauth2',
    },
    'sage': {
        'client_id': os.environ.get('SAGE_CLIENT_ID', ''),
        'client_secret': os.environ.get('SAGE_CLIENT_SECRET', ''),
        'scope': 'full_access',
        'redirect_uri': os.environ.get('SAGE_REDIRECT_URI', 'http://localhost:3000/admin/finance-integrations/oauth-callback'),
    },
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'finance_integrations.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'finance_integrations': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Increased from 10 to 100 to show more shifts
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Disable CSRF for API endpoints (mobile app uses JWT, not cookies)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}

# Add custom user model setting
AUTH_USER_MODEL = 'api.User'

# Google Maps API Key
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')

# ==========================================
# CELERY CONFIGURATION
# ==========================================

# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Celery Settings
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Celery Database Results Backend (alternative to Redis for results)
CELERY_RESULT_BACKEND_DB_URL = f"db+postgresql://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', 'postgres')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'security_management')}"

# Use Redis by default, but allow database backend via environment variable
if os.getenv('CELERY_USE_DB_BACKEND', 'False') == 'True':
    CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND_DB_URL

# Cache configuration (using Redis when available)
try:
    import django_redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
except ImportError:
    # Fallback to local memory cache if Redis is not available
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Cache timeout for report data (in seconds)
CACHE_TIMEOUT_REPORT_DATA = 60 * 15  # 15 minutes
CACHE_TIMEOUT_REPORT_JOBS = 60 * 5   # 5 minutes

# Celery Task Configuration
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_ACKS_LATE = True

# Result backend settings
CELERY_RESULT_EXPIRES = 3600  # 1 hour
CELERY_RESULT_PERSISTENT = True

# Retry settings
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # seconds
CELERY_TASK_MAX_RETRIES = 3

# Security settings
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_IGNORE_RESULT = False

# Report generation specific settings
REPORT_FILE_RETENTION_DAYS = int(os.getenv('REPORT_FILE_RETENTION_DAYS', '7'))
REPORT_MAX_CONCURRENT_JOBS = int(os.getenv('REPORT_MAX_CONCURRENT_JOBS', '3'))
REPORT_BATCH_SIZE = int(os.getenv('REPORT_BATCH_SIZE', '1000'))

# File storage settings for reports
REPORT_STORAGE_PATH = os.path.join(MEDIA_ROOT, 'reports')
REPORT_TEMP_PATH = os.path.join(REPORT_STORAGE_PATH, 'temp')

# Email settings for report notifications
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@security-management.com')

# ==========================================
# DJANGO CHANNELS CONFIGURATION
# ==========================================

# ASGI Application
ASGI_APPLICATION = 'core.asgi.application'

# Channels Layer Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
            'symmetric_encryption_keys': [SECRET_KEY],
        },
    },
}

# WebSocket settings
WEBSOCKET_URL = os.getenv('WEBSOCKET_URL', 'ws://localhost:8000/ws/')

# WebSocket authentication timeout (seconds)
WEBSOCKET_AUTH_TIMEOUT = 30

# WebSocket heartbeat interval (seconds)
WEBSOCKET_HEARTBEAT_INTERVAL = 30

# Maximum WebSocket connections per user
WEBSOCKET_MAX_CONNECTIONS_PER_USER = 5

# WebSocket message size limits (bytes)
WEBSOCKET_MAX_MESSAGE_SIZE = 1024 * 1024  # 1MB
