"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url
import sentry_sdk

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError('DJANGO_SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Sentry Error Tracking
SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        send_default_pii=True,
        traces_sample_rate=0.2 if not DEBUG else 1.0,
        profiles_sample_rate=0.1 if not DEBUG else 1.0,
        environment='development' if DEBUG else 'production',
    )

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,172.16.32.165,10.0.4.21,10.0.4.27,192.168.0.127,192.168.1.82,10.167.91.217').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django_filters',
    # Django Channels
    'channels',
    # Celery apps
    'django_celery_beat',
    'django_celery_results',
    # Project apps
    'api',
    'shifts',
    'finance_integrations',
    'leave_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.tenant_middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Exempt API endpoints from CSRF (mobile app uses JWT tokens, not cookies)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://10.0.4.21:8081',
    'http://10.0.4.21:19000',
    'http://10.0.4.27:8081',
    'http://10.0.4.27:19000',
    # Production admin dashboard
    'https://admin.meadsecurity.co.uk',
    'https://guard-ten.vercel.app',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'security_management'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Support DATABASE_URL for Render/Heroku deployment
# This overrides the above settings if DATABASE_URL is provided
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )

# Asyncpg database configuration
ASYNCPG_DATABASE = {
    'database': os.getenv('DB_NAME', 'security_management'),
    'user': os.getenv('DB_USER', 'postgres'),
    'password': os.getenv('DB_PASSWORD', 'postgres'),
    'host': os.getenv('DB_HOST', 'localhost'),
    'port': int(os.getenv('DB_PORT', '5432')),
    'command_timeout': 60,  # timeout for operations in seconds
    'min_size': 10,  # minimum pool size
    'max_size': 20,  # maximum pool size
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing Configuration
# Using bcrypt for industry-standard password security
# Fallback to PBKDF2 for backward compatibility with existing users
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # Primary: bcrypt with SHA256
    'django.contrib.auth.hashers.BCryptPasswordHasher',        # Fallback: standard bcrypt
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',        # Fallback: existing users (PBKDF2)
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',    # Legacy support
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration for serving static files in production
# This enables compression and caching for better performance
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings - Secure configuration
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in debug mode
CORS_ALLOW_CREDENTIALS = True

# Production CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "https://localhost:3001",
    "https://127.0.0.1:3001",
    # Production frontend (Vercel)
    "https://guard-ten.vercel.app",
    # Production admin dashboard (custom domain)
    "https://admin.meadsecurity.co.uk",
]

# CORS headers and methods configuration
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Add any additional production origins from environment
additional_origins = os.getenv('CORS_ADDITIONAL_ORIGINS')
if additional_origins:
    CORS_ALLOWED_ORIGINS.extend(additional_origins.split(','))

# Finance Integrations OAuth Settings
FINANCE_OAUTH_SETTINGS = {
    'xero': {
        'client_id': os.environ.get('XERO_CLIENT_ID', ''),
        'client_secret': os.environ.get('XERO_CLIENT_SECRET', ''),
        'scope': 'accounting.transactions accounting.contacts.read accounting.settings payroll.employees payroll.payruns payroll.settings files',
        'redirect_uri': os.environ.get('XERO_REDIRECT_URI', 'http://localhost:3000/admin/finance-integrations/oauth-callback'),
    },
    'quickbooks': {
        'client_id': os.environ.get('QUICKBOOKS_CLIENT_ID', ''),
        'client_secret': os.environ.get('QUICKBOOKS_CLIENT_SECRET', ''),
        'scope': 'com.intuit.quickbooks.accounting',
        'redirect_uri': os.environ.get('QUICKBOOKS_REDIRECT_URI', 'http://localhost:3000/admin/finance-integrations/oauth-callback'),
        'discovery_document': 'https://appcenter.intuit.com/connect/oauth2',
    },
    'sage': {
        'client_id': os.environ.get('SAGE_CLIENT_ID', ''),
        'client_secret': os.environ.get('SAGE_CLIENT_SECRET', ''),
        'scope': 'full_access',
        'redirect_uri': os.environ.get('SAGE_REDIRECT_URI', 'http://localhost:3000/admin/finance-integrations/oauth-callback'),
    },
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'finance_integrations.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'finance_integrations': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'shifts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'leave_management': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Sprint 3: Custom JWT authentication that reads from httpOnly cookies
        'api.authentication.CookieJWTAuthentication',
        # Keep SessionAuthentication for Django admin and browsable API
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '120/minute',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Increased from 10 to 100 to show more shifts
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Disable CSRF for API endpoints (mobile app uses JWT, not cookies)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    # Cookie-based authentication settings (Sprint 3: Security Enhancement)
    'AUTH_COOKIE': 'access_token',  # Name of the access token cookie
    'AUTH_COOKIE_REFRESH': 'refresh_token',  # Name of the refresh token cookie
    'AUTH_COOKIE_SECURE': not DEBUG,  # Use secure cookies in production (HTTPS only)
    'AUTH_COOKIE_HTTP_ONLY': True,  # Prevent JavaScript access (XSS protection)
    'AUTH_COOKIE_PATH': '/',  # Cookie path
    'AUTH_COOKIE_SAMESITE': 'None' if not DEBUG else 'Lax',  # None for cross-site (Vercel→Render), Lax for localhost
    'AUTH_COOKIE_DOMAIN': 'localhost' if DEBUG else None,  # Use localhost for development to work across ports
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
}

# Add custom user model setting
AUTH_USER_MODEL = 'api.User'

# Google Maps API Key
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')

# Social Authentication
APPLE_CLIENT_ID = os.getenv('APPLE_CLIENT_ID')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_IOS_CLIENT_ID = os.getenv('GOOGLE_IOS_CLIENT_ID')
GOOGLE_ANDROID_CLIENT_ID = os.getenv('GOOGLE_ANDROID_CLIENT_ID')

# ==========================================
# CELERY CONFIGURATION
# ==========================================

# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Celery Settings
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Celery Database Results Backend (alternative to Redis for results)
CELERY_RESULT_BACKEND_DB_URL = f"db+postgresql://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', 'postgres')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'security_management')}"

# Use Redis by default, but allow database backend via environment variable
if os.getenv('CELERY_USE_DB_BACKEND', 'False') == 'True':
    CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND_DB_URL

# Cache configuration (using Redis when available)
try:
    import django_redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
except ImportError:
    # Fallback to local memory cache if Redis is not available
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Cache timeout for report data (in seconds)
CACHE_TIMEOUT_REPORT_DATA = 60 * 15  # 15 minutes
CACHE_TIMEOUT_REPORT_JOBS = 60 * 5   # 5 minutes

# Celery Task Configuration
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_ACKS_LATE = True

# Result backend settings
CELERY_RESULT_EXPIRES = 3600  # 1 hour
CELERY_RESULT_PERSISTENT = True

# Retry settings
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # seconds
CELERY_TASK_MAX_RETRIES = 3

# Security settings
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_IGNORE_RESULT = False

# Celery Beat Schedule (periodic tasks)
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    'update-expired-sia-licenses': {
        'task': 'api.tasks.update_expired_sia_licenses',
        'schedule': crontab(hour=0, minute=15),
    },
    'detect-attendance-exceptions': {
        'task': 'api.tasks.detect_attendance_exceptions',
        'schedule': crontab(minute='*/15'),
    },
    'process-auto-checkouts': {
        'task': 'api.tasks.process_auto_checkouts',
        'schedule': crontab(minute='*/5'),
    },
    'process-monthly-leave-accruals': {
        'task': 'api.tasks.process_monthly_leave_accruals',
        'schedule': crontab(day_of_month=1, hour=2, minute=0),
    },
    'hard-delete-expired-accounts': {
        'task': 'api.tasks.hard_delete_expired_accounts',
        'schedule': crontab(hour=2, minute=30),
    },
    'create-weekly-payroll-run': {
        'task': 'api.tasks.create_weekly_payroll_run',
        # Mondays at 06:00 UTC — generates the previous ISO week's run for
        # officers whose StaffProfile.pay_frequency='weekly' (the default).
        'schedule': crontab(day_of_week='mon', hour=6, minute=0),
    },
    'create-monthly-payroll-run': {
        'task': 'api.tasks.create_monthly_payroll_run',
        # 1st of each month at 06:00 UTC — generates the previous calendar
        # month's run for officers whose pay_frequency='monthly'.
        'schedule': crontab(day_of_month=1, hour=6, minute=0),
    },
    'flag-missed-capacity-checks': {
        'task': 'api.tasks.flag_missed_capacity_checks',
        # Every 5 minutes — detects capacity-check windows that elapsed with
        # no log on monitored shifts, creates a permanent miss record and
        # alerts managers.
        'schedule': crontab(minute='*/5'),
    },
}

# Report generation specific settings
REPORT_FILE_RETENTION_DAYS = int(os.getenv('REPORT_FILE_RETENTION_DAYS', '7'))
REPORT_MAX_CONCURRENT_JOBS = int(os.getenv('REPORT_MAX_CONCURRENT_JOBS', '3'))
REPORT_BATCH_SIZE = int(os.getenv('REPORT_BATCH_SIZE', '1000'))

# File storage settings for reports
REPORT_STORAGE_PATH = os.path.join(MEDIA_ROOT, 'reports')
REPORT_TEMP_PATH = os.path.join(REPORT_STORAGE_PATH, 'temp')

# Email settings for report notifications and password reset
# IMPORTANT: Set these in your .env file, never commit credentials!
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'info@meadsecurity.co.uk')

# Multiple sender emails for different purposes
HR_FROM_EMAIL = os.getenv('HR_FROM_EMAIL', 'hr@meadsecurity.co.uk')
INFO_FROM_EMAIL = os.getenv('INFO_FROM_EMAIL', 'info@meadsecurity.co.uk')
PAYMENT_FROM_EMAIL = os.getenv('PAYMENT_FROM_EMAIL', 'payment@meadsecurity.co.uk')

# Frontend URL for password reset emails
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# ==========================================
# DJANGO CHANNELS CONFIGURATION
# ==========================================

# ASGI Application
ASGI_APPLICATION = 'core.asgi.application'

# Channels Layer Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
            'symmetric_encryption_keys': [SECRET_KEY],
        },
    },
}

# WebSocket settings
WEBSOCKET_URL = os.getenv('WEBSOCKET_URL', 'ws://localhost:8000/ws/')

# WebSocket authentication timeout (seconds)
WEBSOCKET_AUTH_TIMEOUT = 30

# WebSocket heartbeat interval (seconds)
WEBSOCKET_HEARTBEAT_INTERVAL = 30

# Maximum WebSocket connections per user
WEBSOCKET_MAX_CONNECTIONS_PER_USER = 5

# WebSocket message size limits (bytes)
WEBSOCKET_MAX_MESSAGE_SIZE = 1024 * 1024  # 1MB

# ==========================================
# PRODUCTION SECURITY SETTINGS
# ==========================================
# These settings are automatically enabled when DEBUG=False

if not DEBUG:
    # HTTPS/SSL settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS settings (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Content security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # Update CORS for production - extend existing list with environment values
    cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    if cors_origins:
        env_origins = [origin.strip() for origin in cors_origins.split(',') if origin.strip()]
        CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS + env_origins))

    # Update CSRF trusted origins for production - extend existing list
    csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins:
        env_csrf_origins = [origin.strip() for origin in csrf_origins.split(',') if origin.strip()]
        CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS + env_csrf_origins))

# ==========================================
# SENTRY ERROR TRACKING
# ==========================================
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        environment=os.getenv('SENTRY_ENVIRONMENT', 'development'),
        traces_sample_rate=0.1 if not DEBUG else 1.0,
        profiles_sample_rate=0.1 if not DEBUG else 1.0,
        send_default_pii=False,
    )

# ==========================================
# POSTHOG ANALYTICS
# ==========================================
POSTHOG_API_KEY = os.getenv('POSTHOG_API_KEY', '')
POSTHOG_HOST = os.getenv('POSTHOG_HOST', 'https://eu.i.posthog.com')

# ==========================================
# WEBHOOK SECURITY
# ==========================================
WEBHOOK_SECRET = os.getenv('WEBHOOK_SECRET', '')
if not WEBHOOK_SECRET and not DEBUG:
    raise ValueError('WEBHOOK_SECRET environment variable is required in production')
