#!/bin/bash

# switch-env.sh - Switch between local development and production environments
#
# Usage:
#   ./switch-env.sh local   - Switch to local development (auto-detects your IP)
#   ./switch-env.sh prod    - Switch to production (Render API)
#   ./switch-env.sh         - Same as 'local' (default)

MODE=${1:-local}

# Detect IP address (works on Mac/Linux)
detect_ip() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS - Prioritize en0 (Wi-Fi) since route can pick up VPN tunnels
        IP=$(ipconfig getifaddr en0 2>/dev/null)

        # Fallback: try en1 (some Macs use this for Wi-Fi)
        [ -z "$IP" ] && IP=$(ipconfig getifaddr en1 2>/dev/null)

        # Last resort: try the default route interface
        [ -z "$IP" ] && IP=$(ipconfig getifaddr $(route get default 2>/dev/null | grep interface | awk '{print $2}') 2>/dev/null)
    else
        # Linux
        IP=$(hostname -I | awk '{print $1}')
    fi
    echo "$IP"
}

ENV_FILE="$(dirname "$0")/.env"

if [ "$MODE" = "local" ]; then
    IP=$(detect_ip)

    if [ -z "$IP" ]; then
        echo "❌ Could not detect IP address. Are you connected to WiFi?"
        exit 1
    fi

    echo "🔧 Switching to LOCAL development..."
    echo "   Detected IP: $IP"
    echo ""

    cat > "$ENV_FILE" << EOF
# Mobile App Environment Configuration
# Generated by switch-env.sh on $(date)

# Backend API Configuration - LOCAL DEVELOPMENT
API_BASE_URL=http://${IP}:8000

# Expo Configuration
EXPO_PROJECT_ID=9d8d1bce-0f46-4c87-99c4-503a32be2113

# Environment
NODE_ENV=development
EOF

    echo "✅ API_BASE_URL=http://${IP}:8000"
    echo ""
    echo "📋 Next steps:"
    echo "   1. Start Redis: brew services start redis"
    echo "   2. Run Daphne (handles HTTP + WebSocket):"
    echo "      cd backend && daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    echo "   3. Restart Expo: npx expo start --clear"
    echo ""
    echo "💡 Your phone and Mac must be on the same WiFi network"
    echo "💡 Use Daphne instead of runserver to enable WebSocket support"

elif [ "$MODE" = "prod" ]; then
    echo "🌐 Switching to PRODUCTION..."
    echo ""

    cat > "$ENV_FILE" << EOF
# Mobile App Environment Configuration
# Generated by switch-env.sh on $(date)

# Backend API Configuration - PRODUCTION
API_BASE_URL=https://mead-security-api.onrender.com

# Expo Configuration
EXPO_PROJECT_ID=9d8d1bce-0f46-4c87-99c4-503a32be2113

# Environment
NODE_ENV=development
EOF

    echo "✅ API_BASE_URL=https://mead-security-api.onrender.com"
    echo ""
    echo "📋 Next step:"
    echo "   Restart Expo: npx expo start --clear"

else
    echo "Usage: ./switch-env.sh [local|prod]"
    echo ""
    echo "  local  - Switch to local development (default)"
    echo "           Auto-detects your Mac's IP address"
    echo ""
    echo "  prod   - Switch to production (Render API)"
    echo "           Uses https://mead-security-api.onrender.com"
    exit 1
fi
