# Generated by Django 5.2 on 2025-08-15 08:43

import django.db.models.deletion
import finance_integrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0020_add_enforcement_visit_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_key",
                    models.CharField(
                        choices=[
                            ("xero", "Xero"),
                            ("quickbooks", "QuickBooks Online"),
                            ("freeagent", "FreeAgent"),
                            ("freshbooks", "FreshBooks"),
                            ("zoho", "Zoho Books"),
                            ("sage", "Sage Business Cloud"),
                            ("wave", "Wave Accounting"),
                            ("netsuite", "NetSuite"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("oauth_client_id", models.CharField(blank=True, max_length=500)),
                (
                    "oauth_client_secret",
                    finance_integrations.models.EncryptedJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "oauth_scopes",
                    models.TextField(
                        blank=True, help_text="Comma-separated OAuth scopes"
                    ),
                ),
                ("api_base_url", models.URLField(blank=True)),
                ("webhook_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounting_providers",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider-specific tenant/company ID",
                        max_length=200,
                    ),
                ),
                (
                    "access_token",
                    finance_integrations.models.EncryptedJSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "refresh_token",
                    finance_integrations.models.EncryptedJSONField(
                        blank=True, null=True
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Setup"),
                            ("connected", "Connected"),
                            ("expired", "Token Expired"),
                            ("error", "Connection Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "is_sandbox",
                    models.BooleanField(
                        default=False, help_text="Use sandbox/demo environment"
                    ),
                ),
                ("auto_sync_invoices", models.BooleanField(default=True)),
                ("auto_sync_payroll", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="finance_integrations.accountingprovider",
                    ),
                ),
            ],
            options={
                "db_table": "provider_connections",
                "ordering": ["-created_at"],
                "unique_together": {("provider", "tenant_id")},
            },
        ),
        migrations.CreateModel(
            name="PayrollExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("payrun", "Pay Run"), ("journal", "Journal Entry")],
                        default="payrun",
                        max_length=20,
                    ),
                ),
                ("pay_period_start", models.DateField()),
                ("pay_period_end", models.DateField()),
                ("provider_payrun_id", models.CharField(blank=True, max_length=100)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_data",
                    models.JSONField(
                        blank=True,
                        help_text="Exported payroll data snapshot",
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, help_text="Provider API response", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exported_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_users",
                    models.ManyToManyField(
                        related_name="payroll_exports", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_exports",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_exports",
                "ordering": ["-exported_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_invoice_id", models.CharField(blank=True, max_length=100)),
                (
                    "provider_invoice_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_data",
                    models.JSONField(
                        blank=True,
                        help_text="Exported invoice data snapshot",
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, help_text="Provider API response", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exported_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="api.invoice",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_exports",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_exports",
                "ordering": ["-exported_at"],
                "unique_together": {("connection", "local_invoice")},
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "event_id",
                    models.CharField(
                        blank=True, help_text="Provider event ID", max_length=100
                    ),
                ),
                ("raw_payload", models.JSONField(help_text="Raw webhook payload")),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Webhook signature for verification",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True, help_text="Processed data from webhook", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_events",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("oauth_connect", "OAuth Connection"),
                            ("oauth_refresh", "Token Refresh"),
                            ("export_invoice", "Export Invoice"),
                            ("export_payroll", "Export Payroll"),
                            ("import_payment", "Import Payment"),
                            ("webhook_process", "Process Webhook"),
                            ("mapping_update", "Update Mapping"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional context data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="finance_integrations.providerconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice_export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="finance_integrations.invoiceexport",
                    ),
                ),
                (
                    "payroll_export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="finance_integrations.payrollexport",
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="finance_integrations.webhookevent",
                    ),
                ),
            ],
            options={
                "db_table": "sync_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EarningsTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_earnings_name",
                    models.CharField(
                        help_text="e.g., 'Regular Hours', 'Special Event Rate'",
                        max_length=100,
                    ),
                ),
                (
                    "local_hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("provider_earnings_code", models.CharField(max_length=50)),
                ("provider_earnings_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings_mappings",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "earnings_type_mappings",
                "ordering": ["local_earnings_name"],
                "unique_together": {("connection", "local_earnings_name")},
            },
        ),
        migrations.CreateModel(
            name="ContactMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("client", "Client/Customer"),
                            ("supplier", "Supplier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_contact_id", models.CharField(max_length=100)),
                ("provider_contact_name", models.CharField(max_length=200)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "local_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_mappings",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "contact_mappings",
                "ordering": ["contact_type", "provider_contact_name"],
                "unique_together": {("connection", "contact_type", "local_user")},
            },
        ),
        migrations.CreateModel(
            name="AccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Account"),
                            ("expense", "Expense Account"),
                            ("liability", "Liability Account"),
                            ("asset", "Asset Account"),
                            ("equity", "Equity Account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("local_account_name", models.CharField(max_length=200)),
                ("provider_account_id", models.CharField(max_length=100)),
                ("provider_account_name", models.CharField(max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_mappings",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "account_mappings",
                "ordering": ["mapping_type", "local_account_name"],
                "unique_together": {
                    ("connection", "mapping_type", "local_account_name")
                },
            },
        ),
        migrations.CreateModel(
            name="VATCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_vat_code", models.CharField(max_length=20)),
                (
                    "local_vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="VAT rate as decimal (e.g., 0.20 for 20%)",
                        max_digits=5,
                    ),
                ),
                ("provider_vat_code", models.CharField(max_length=50)),
                ("provider_vat_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_mappings",
                        to="finance_integrations.providerconnection",
                    ),
                ),
            ],
            options={
                "db_table": "vat_code_mappings",
                "ordering": ["local_vat_code"],
                "unique_together": {("connection", "local_vat_code")},
            },
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["event_type", "-received_at"],
                name="webhook_eve_event_t_36c607_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["status", "-received_at"], name="webhook_eve_status_6266fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["operation", "-created_at"], name="sync_logs_operati_75151b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["level", "-created_at"], name="sync_logs_level_4d29c2_idx"
            ),
        ),
    ]
