# Generated by Django 5.2 on 2026-04-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_billing_payroll_alignment"),
        ("finance_integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInvoiceExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_invoice_id", models.CharField(blank=True, max_length=100)),
                (
                    "provider_invoice_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_data",
                    models.JSONField(
                        blank=True,
                        help_text="Exported invoice data snapshot",
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, help_text="Provider API response", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_invoice_exports",
                        to="finance_integrations.providerconnection",
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exported_client_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="api.clientinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "client_invoice_exports",
                "ordering": ["-exported_at"],
                "unique_together": {("connection", "local_invoice")},
            },
        ),
    ]
