# Generated by Django 5.2 on 2025-09-13 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0020_add_enforcement_visit_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the leave type (e.g., 'Annual Leave', 'Sick Leave')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the leave type (e.g., 'AL', 'SL')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of this leave type"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#007bff",
                        help_text="HEX color code for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this leave type is currently available",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Whether requests for this leave type require manager approval",
                    ),
                ),
                (
                    "min_notice_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum notice required in days before leave start date",
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum consecutive days allowed for this leave type",
                        null=True,
                    ),
                ),
                (
                    "employment_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Employment types eligible for this leave type (empty = all types)",
                        related_name="leave_types",
                        to="api.employmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "db_table": "leave_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this leave policy",
                        max_length=200,
                    ),
                ),
                (
                    "accrual_method",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Accrual"),
                            ("annual", "Annual Grant"),
                            ("per_shift", "Per Shift Worked"),
                            ("length_of_service", "Based on Length of Service"),
                            ("none", "No Automatic Accrual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "accrual_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Accrual rate (days per period, based on accrual method)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "max_accrual_per_year",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum days that can be accrued per year",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "max_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum balance that can be accumulated",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "service_brackets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Service brackets for length-of-service accrual: [{'months': 12, 'rate': 20}, ...]",
                    ),
                ),
                (
                    "carryover_method",
                    models.CharField(
                        choices=[
                            ("none", "No Carryover"),
                            ("full", "Full Carryover"),
                            ("partial", "Partial Carryover"),
                            ("use_or_lose", "Use or Lose by Date"),
                        ],
                        default="partial",
                        max_length=15,
                    ),
                ),
                (
                    "carryover_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum days that can be carried over (for partial carryover)",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "carryover_expiry_months",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Months after which carried over leave expires",
                    ),
                ),
                (
                    "probation_months",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Months of employment before leave accrual begins",
                    ),
                ),
                (
                    "min_employment_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum days of employment before leave can be taken",
                    ),
                ),
                (
                    "allow_negative_balance",
                    models.BooleanField(
                        default=False,
                        help_text="Allow taking leave beyond current balance",
                    ),
                ),
                (
                    "negative_balance_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum negative balance allowed (if enabled)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this policy is currently active",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when this policy becomes effective",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this policy expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "employment_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Employment types this policy applies to (empty = all types)",
                        related_name="leave_policies",
                        to="api.employmenttype",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="leave_management.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Policy",
                "verbose_name_plural": "Leave Policies",
                "db_table": "leave_policies",
                "ordering": ["leave_type__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Calendar year this entitlement applies to"
                    ),
                ),
                (
                    "annual_entitlement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total days entitled for this year",
                        max_digits=6,
                    ),
                ),
                (
                    "carried_over",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days carried over from previous year",
                        max_digits=6,
                    ),
                ),
                (
                    "accrued_to_date",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days accrued so far this year",
                        max_digits=6,
                    ),
                ),
                (
                    "used_to_date",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days used so far this year",
                        max_digits=6,
                    ),
                ),
                (
                    "last_accrual_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last accrual calculation",
                        null=True,
                    ),
                ),
                (
                    "carryover_expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when carried over leave expires",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="leave_management.leavepolicy",
                    ),
                ),
            ],
            options={
                "db_table": "leave_entitlements",
                "ordering": ["-year", "policy__leave_type__name"],
                "indexes": [
                    models.Index(
                        fields=["user", "year"], name="leave_entit_user_id_0a602e_idx"
                    ),
                    models.Index(
                        fields=["policy", "year"], name="leave_entit_policy__72eda6_idx"
                    ),
                    models.Index(
                        fields=["last_accrual_date"],
                        name="leave_entit_last_ac_d360a1_idx",
                    ),
                ],
                "unique_together": {("user", "policy", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="leavepolicy",
            index=models.Index(
                fields=["leave_type", "is_active"],
                name="leave_polic_leave_t_a05eaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leavepolicy",
            index=models.Index(
                fields=["effective_date", "expiry_date"],
                name="leave_polic_effecti_e18e58_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavepolicy",
            unique_together={("name", "leave_type")},
        ),
    ]
