# Generated by Django 5.2 on 2025-09-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0002_optimized_leave_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optimizedleavepolicy",
            name="employment_types",
        ),
        migrations.RemoveField(
            model_name="optimizedleavepolicy",
            name="leave_type",
        ),
        migrations.RemoveField(
            model_name="optimizedleavetype",
            name="employment_types",
        ),
        migrations.DeleteModel(
            name="OptimizedLeaveEntitlement",
        ),
        migrations.DeleteModel(
            name="OptimizedLeavePolicy",
        ),
        migrations.DeleteModel(
            name="OptimizedLeaveType",
        ),
    ]
