# Generated by Django 5.2 on 2025-09-13 21:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_add_enforcement_visit_model"),
        (
            "leave_management",
            "0003_remove_optimizedleavepolicy_employment_types_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackoutPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this blackout period",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the restriction"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the blackout period"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of the blackout period"),
                ),
                (
                    "restriction_level",
                    models.CharField(
                        choices=[
                            ("no_requests", "No Leave Requests Allowed"),
                            ("emergency_only", "Emergency Leave Only"),
                            ("manager_approval", "Requires Manager Approval"),
                            ("limit_percentage", "Limit by Percentage of Staff"),
                        ],
                        default="no_requests",
                        max_length=20,
                    ),
                ),
                (
                    "max_staff_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum percentage of staff allowed on leave (for limit_percentage)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "allow_manager_override",
                    models.BooleanField(
                        default=True,
                        help_text="Allow managers to override this restriction",
                    ),
                ),
                (
                    "override_reason_required",
                    models.BooleanField(
                        default=True, help_text="Require reason for manager override"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this blackout period is active"
                    ),
                ),
                (
                    "leave_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific leave types (leave empty for all types)",
                        related_name="blackout_periods",
                        to="leave_management.leavetype",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific venue (leave empty for system-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_periods",
                        to="api.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blackout Period",
                "verbose_name_plural": "Blackout Periods",
                "db_table": "blackout_periods",
                "ordering": ["start_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="blackout_pe_start_d_b868dd_idx",
                    ),
                    models.Index(
                        fields=["venue", "is_active"],
                        name="blackout_pe_venue_i_1d2572_idx",
                    ),
                    models.Index(
                        fields=["is_active", "start_date"],
                        name="blackout_pe_is_acti_7c6bab_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Calendar year this balance applies to"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Balance at start of year (including carryover)",
                        max_digits=6,
                    ),
                ),
                (
                    "accrued_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total accrued during the year",
                        max_digits=6,
                    ),
                ),
                (
                    "used_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total used during the year",
                        max_digits=6,
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total pending approval",
                        max_digits=6,
                    ),
                ),
                (
                    "adjustment_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Manual adjustments (positive or negative)",
                        max_digits=6,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When balance was last recalculated"
                    ),
                ),
                (
                    "last_accrual_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last accrual processing",
                        null=True,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        help_text="Type of leave this balance tracks",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="leave_management.leavetype",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        help_text="Staff member whose balance this tracks",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "db_table": "leave_balances",
                "ordering": ["-year", "leave_type__name"],
                "indexes": [
                    models.Index(
                        fields=["staff_user", "year"],
                        name="leave_balan_staff_u_2d5340_idx",
                    ),
                    models.Index(
                        fields=["leave_type", "year"],
                        name="leave_balan_leave_t_5ffa90_idx",
                    ),
                    models.Index(
                        fields=["year", "last_updated"],
                        name="leave_balan_year_d018e2_idx",
                    ),
                ],
                "unique_together": {("staff_user", "leave_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(help_text="First day of leave")),
                ("end_date", models.DateField(help_text="Last day of leave")),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("full_day", "Full Day"),
                            ("half_day_am", "Half Day (Morning)"),
                            ("half_day_pm", "Half Day (Afternoon)"),
                            ("hours", "Specific Hours"),
                        ],
                        default="full_day",
                        max_length=15,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for hourly leave requests",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="End time for hourly leave requests",
                        null=True,
                    ),
                ),
                (
                    "days_requested",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total days being requested",
                        max_digits=5,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave request")),
                (
                    "emergency",
                    models.BooleanField(
                        default=False,
                        help_text="Emergency leave request (reduced notice)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was submitted for approval",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was approved/rejected",
                        null=True,
                    ),
                ),
                (
                    "manager_notes",
                    models.TextField(
                        blank=True, help_text="Manager's notes on the approval decision"
                    ),
                ),
                (
                    "balance_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether leave balance has been deducted",
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether notification has been sent to staff",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved/rejected the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        help_text="Type of leave being requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="leave_management.leavetype",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        help_text="Staff member submitting the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["staff_user", "status"],
                        name="leave_reque_staff_u_98e233_idx",
                    ),
                    models.Index(
                        fields=["leave_type", "start_date"],
                        name="leave_reque_leave_t_6d531f_idx",
                    ),
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="leave_reque_status_0e0d66_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="leave_reque_start_d_08703b_idx",
                    ),
                ],
            },
        ),
    ]
