# Generated by Django 5.2 on 2025-10-03 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0005_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config_key",
                    models.CharField(
                        help_text="Unique identifier for this configuration type",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        default=dict, help_text="Configuration data as JSON"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this configuration controls",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "leave_system_config",
                "ordering": ["config_key"],
            },
        ),
    ]
